import {cosmetics} from '@/lib/cosmetics';
import {getD1,getSessionUser,isManager,profilePayload,maintenanceBlocked} from '@/lib/s27-server';
const scope=(id:string)=>id.startsWith('lab:')&&!['lab:admin','lab:manager'].includes(id)?'lab':'live';
function randomCode(){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';let out='';while(out.length<16){for(const n of crypto.getRandomValues(new Uint8Array(32))){if(n<248)out+=alphabet[n%62];if(out.length===16)break;}}return out.match(/.{4}/g)!.join('-');}
export async function GET(r:Request){try{const u=await getSessionUser(r);if(!u||!(await isManager(u.discord_id)))return Response.json({error:'Доступ только менеджеру'},{status:403});const db=getD1();const codes=await db.prepare('SELECT * FROM reward_codes WHERE (scope=? OR creator=?) ORDER BY created_at DESC LIMIT 300').bind(scope(u.discord_id),u.discord_id).all();const redemptions=await db.prepare('SELECT r.*,c.code,c.reward_type,c.reward_item,c.reward_amount,u.display_name FROM code_redemptions r JOIN reward_codes c ON c.id=r.code_id JOIN users u ON u.discord_id=r.user_id WHERE (c.scope=? OR c.creator=?) ORDER BY r.created_at DESC LIMIT 100').bind(scope(u.discord_id),u.discord_id).all();return Response.json({codes:codes.results,redemptions:redemptions.results},{headers:{'Cache-Control':'private, no-store'}});}catch{return Response.json({error:'Коды временно недоступны'},{status:503});}}
export async function POST(r:Request){const u=await getSessionUser(r);if(!u)return Response.json({error:'Войдите в профиль'},{status:401});if(await maintenanceBlocked(u.discord_id))return Response.json({error:'Сайт временно приостановлен'},{status:503});try{return await handleRewardCode(await r.json(),u.discord_id);}catch{return Response.json({error:'Неверный запрос'},{status:400});}}
export async function handleRewardCode(b:any,userId:string){try{
 const u={discord_id:userId},db=getD1(),now=Date.now(),s=scope(userId);
 if(b.action==='redeem'){
  if(typeof b.code!=='string'||b.code.length>128)return Response.json({error:'Введите код'},{status:400});
  const attempts=await db.prepare('INSERT INTO login_limits(key,attempts,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET attempts=CASE WHEN expires<? THEN 1 ELSE attempts+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END RETURNING attempts').bind('redeem:'+u.discord_id,now+900000,now,now).first<any>();if(attempts.attempts>30)return Response.json({error:'Слишком много попыток. Повторите через 15 минут.'},{status:429});
  const c=await db.prepare("SELECT * FROM reward_codes WHERE (scope=? OR creator IN ('lab:admin','lab:manager')) AND code=? ORDER BY CASE WHEN scope=? THEN 0 ELSE 1 END LIMIT 1").bind(s,b.code.trim().normalize('NFC'),s).first<any>();if(!c)return Response.json({error:'Код не найден. Проверьте регистр букв.'},{status:404});
  if(c.reward_type==='cosmetic'&&await db.prepare('SELECT item_id FROM user_cosmetics WHERE user_id=? AND item_id=?').bind(u.discord_id,c.reward_item).first())return Response.json({error:'Это украшение уже есть в гардеробе. Код не потрачен.'},{status:409});
  try{await db.batch([
   db.prepare('UPDATE reward_codes SET uses=uses+1 WHERE id=? AND active=1 AND uses<max_uses AND NOT EXISTS(SELECT 1 FROM code_redemptions WHERE code_id=? AND user_id=?)').bind(c.id,c.id,u.discord_id),
   db.prepare("INSERT INTO operations(id,user_id,action,result,valid,created_at) VALUES (?,?,'code.redeem','{}',changes(),?)").bind('redeem:'+c.id+':'+u.discord_id,u.discord_id,now),
   db.prepare('INSERT INTO code_redemptions(code_id,user_id,coupons,created_at) VALUES (?,?,?,?)').bind(c.id,u.discord_id,c.coupons,now),
   db.prepare('UPDATE users SET tokens=tokens+?,fragments=fragments+?,updated_at=? WHERE discord_id=?').bind(c.coupons,c.reward_type==='tokens'?c.reward_amount:0,now,u.discord_id),
   ...(c.reward_type==='cosmetic'?[db.prepare('INSERT INTO user_cosmetics(user_id,item_id,created_at) VALUES (?,?,?)').bind(u.discord_id,c.reward_item,now)]:[]),
   db.prepare("INSERT INTO audit_log(actor_id,action,target_id,payload,created_at) VALUES (?,'code.redeem',?,?,?)").bind(u.discord_id,u.discord_id,JSON.stringify({codeId:c.id,coupons:c.coupons}),now),
  ]);}catch{return Response.json({error:'Код уже использован вами, отключён или исчерпан'},{status:409});}
  return Response.json({ok:true,coupons:c.coupons,rewardType:c.reward_type,rewardAmount:c.reward_amount,rewardItem:c.reward_item,profile:await profilePayload(u.discord_id)});
 }
 if(!(await isManager(u.discord_id)))return Response.json({error:'Доступ только менеджеру'},{status:403});
 if(b.action==='disable'){const result=await db.batch([db.prepare('UPDATE reward_codes SET active=0 WHERE id=? AND (scope=? OR creator=?) AND active=1').bind(b.id,s,u.discord_id),db.prepare("INSERT INTO audit_log(actor_id,action,target_id,payload,created_at) SELECT ?,'code.disable',?,?,? WHERE changes()=1").bind(u.discord_id,u.discord_id,JSON.stringify({codeId:b.id}),now)]);return Response.json({ok:result[0].meta.changes>0});}
 const rewardType=b.rewardType||'coupons';if(!['coupons','tokens','cosmetic'].includes(rewardType)||rewardType==='tokens'&&(!Number.isInteger(b.rewardAmount)||b.rewardAmount<1||b.rewardAmount>100000)||rewardType==='cosmetic'&&!cosmetics.some(c=>c.id===b.rewardItem))return Response.json({error:'Проверьте награду'},{status:400});
 if(b.action!=='create'||!['prize','community'].includes(b.kind)||(rewardType==='coupons'&&(!Number.isInteger(b.coupons)||b.coupons<1||b.coupons>15))||!Number.isInteger(b.count)||b.count<1||b.count>15||typeof b.code!=='string'||b.code.length>128||typeof b.note!=='string'||b.note.length>300||typeof b.requestId!=='string'||!/^[\da-f-]{36}$/i.test(b.requestId))return Response.json({error:'Проверьте поля: 1–15 купонов, 1–15 кодов'},{status:400});
 const max=b.kind==='prize'?1:b.maxUses;if(!Number.isInteger(max)||max<1||max>10000)return Response.json({error:'Лимит участников: от 1 до 10000'},{status:400});
 const custom=b.code.trim().normalize('NFC');if(custom&&b.count!==1)return Response.json({error:'Свой код можно создать только по одному'},{status:400});
 const op='code-create:'+u.discord_id+':'+b.requestId,previous=await db.prepare('SELECT result FROM operations WHERE id=?').bind(op).first<any>();if(previous)return Response.json(JSON.parse(previous.result));
 const codes=Array.from({length:b.count},()=>({id:crypto.randomUUID(),code:custom||randomCode()})),result={ok:true,codes};
 try{await db.batch([db.prepare("INSERT INTO operations(id,user_id,action,result,valid,created_at) VALUES (?,?,'code.create',?,1,?)").bind(op,u.discord_id,JSON.stringify(result),now),...codes.map(c=>db.prepare('INSERT INTO reward_codes(id,code,scope,kind,coupons,max_uses,uses,active,creator,note,created_at,reward_type,reward_item,reward_amount) VALUES (?,?,?,?,?,?,0,1,?,?,?,?,?,?)').bind(c.id,c.code,s,b.kind,rewardType==='coupons'?b.coupons:0,max,u.discord_id,b.note.trim(),now,rewardType,rewardType==='cosmetic'?b.rewardItem:'',rewardType==='tokens'?b.rewardAmount:0)),db.prepare("INSERT INTO audit_log(actor_id,action,target_id,payload,created_at) VALUES (?,'code.create',?,?,?)").bind(u.discord_id,u.discord_id,JSON.stringify({count:b.count,coupons:b.coupons,maxUses:max}),now)]);}catch{const raced=await db.prepare('SELECT result FROM operations WHERE id=?').bind(op).first<any>();if(raced)return Response.json(JSON.parse(raced.result));return Response.json({error:'Такой код уже существует. Выберите другой.'},{status:409});}
 return Response.json(result,{headers:{'Cache-Control':'private, no-store'}});
 }catch{return Response.json({error:'Не удалось выполнить действие. Попробуйте снова.'},{status:503});}}
