import {getD1,getSessionUser,hasAdminAccess,profilePayload} from '@/lib/s27-server';
import {scopeFor,communityConfig,configGuard} from '@/lib/community';
import {pool,salvage,products} from '@/lib/economy';
import {uniqueCards} from '@/lib/collection-rewards';
import {cosmetics} from '@/lib/cosmetics';
function validate(c:any){
 if(!c||!Array.isArray(c.seasons)||!c.seasons.length||c.seasons.length>30||!Array.isArray(c.sets)||c.sets.length>50||!Array.isArray(c.events)||c.events.length>100||!Array.isArray(c.products)||c.products.length!==products.length)throw Error('Неверная конфигурация');
 for(const list of [c.seasons,c.sets,c.events,c.products]){if(new Set(list.map((x:any)=>x.id)).size!==list.length)throw Error('Повторяется код записи');for(const x of list)if(typeof x.id!=='string'||!/^[a-z0-9_-]{1,64}$/.test(x.id))throw Error('Неверный код записи');}
 for(const x of [...c.seasons,...c.sets,...c.events])if(typeof x.name!=='string'||!x.name.trim()||x.name.length>100)throw Error('Укажите название до 100 символов');
 for(const x of [...c.seasons,...c.sets])if(!Array.isArray(x.cards)||x.cards.length>pool.length||new Set(x.cards).size!==x.cards.length||x.cards.some((s:any)=>!pool.some(p=>p[0]===s)))throw Error('Проверьте список карточек');
 for(const x of c.seasons)if(!['draft','active','archived'].includes(x.status)||!/^#[a-f0-9]{6}$/i.test(x.accent)||typeof x.image!=='string'||!/^\/(cosmetics|hero)\/[a-zA-Z0-9_-]+\.(webp|png|jpg)$/.test(x.image)||typeof x.description!=='string'||x.description.length>1000)throw Error('Проверьте оформление сезона');
 const active=c.seasons.filter((x:any)=>x.status==='active');if(active.length!==1||active[0].id!==c.activeSeason||[0,1,2,3,4].some(r=>!pool.some(p=>p[1]===r&&active[0].cards.includes(p[0]))))throw Error('Нужен один активный сезон с картами каждой редкости');
 for(const x of c.sets)if(!x.cards.length||!['none','coupons','tokens','cosmetic'].includes(x.rewardKind)||!Number.isInteger(x.rewardAmount)||x.rewardAmount<0||x.rewardAmount>10000||(x.rewardKind==='cosmetic'&&!cosmetics.some(p=>p.id===x.rewardItem))||(['coupons','tokens'].includes(x.rewardKind)&&x.rewardAmount<1))throw Error('Проверьте комплект и награду');
 for(const x of c.events)if(typeof x.description!=='string'||x.description.length>2000||typeof x.open!=='boolean'||(x.open&&!x.description.trim())||!Number.isInteger(x.coupons)||x.coupons<1||x.coupons>100)throw Error('Проверьте условия события и количество купонов');
 for(const x of c.products)if(!products.some(p=>p.id===x.id)||typeof x.available!=='boolean'||typeof x.conditions!=='string'||!x.conditions.trim()||x.conditions.length>1000)throw Error('Укажите условия выдачи каждого приза');
}
export async function GET(r:Request){try{const u=await getSessionUser(r),scope=scopeFor(u?.discord_id),db=getD1();const {config,raw}=await communityConfig(scope);const admin=new URL(r.url).searchParams.get('admin')==='1';if(admin&&(!u||!(await hasAdminAccess(u.discord_id))))return Response.json({error:'Нет доступа'},{status:403});if(!admin)config.seasons=config.seasons.filter((s:any)=>s.status!=='draft');if(!u)return Response.json({config,locks:[],claims:[],entries:[],history:[]},{headers:{'Cache-Control':'no-store'}});
 const locks=await db.prepare('SELECT card_slug FROM card_locks WHERE user_id=?').bind(u.discord_id).all();const claims=await db.prepare('SELECT set_id,reward FROM collection_claims WHERE user_id=?').bind(u.discord_id).all();const entries=await (admin?db.prepare('SELECT e.*,u.display_name FROM event_entries e JOIN users u ON u.discord_id=e.user_id WHERE e.scope=? ORDER BY e.created_at DESC LIMIT 200').bind(scope):db.prepare('SELECT * FROM event_entries WHERE user_id=? ORDER BY created_at DESC').bind(u.discord_id)).all();const before=Number(new URL(r.url).searchParams.get('before'))||Number.MAX_SAFE_INTEGER;
 const q=(new URL(r.url).searchParams.get('q')||'').trim().replace(/^@/,'').slice(0,100);
 const pattern='%'+q.replace(/[\\%_]/g,'\\$&')+'%';
 const history=admin?await db.prepare("SELECT a.*,u.username,u.display_name FROM audit_log a LEFT JOIN users u ON u.discord_id=a.target_id WHERE a.id<? AND ((?='lab' AND a.target_id LIKE 'lab:%') OR (?='live' AND (a.target_id NOT LIKE 'lab:%' OR a.target_id IS NULL))) AND (?='' OR a.target_id=? OR a.actor_id=? OR u.username LIKE ? ESCAPE '\\' OR u.display_name LIKE ? ESCAPE '\\') ORDER BY a.id DESC LIMIT 50").bind(before,scope,scope,q,q,q,pattern,pattern).all():{results:[]};return Response.json({config,revision:admin?raw:undefined,locks:locks.results.map((x:any)=>x.card_slug),claims:claims.results,entries:entries.results,history:history.results},{headers:{'Cache-Control':'private, no-store'}});
 }catch{return Response.json({error:'Не удалось загрузить данные. Попробуйте ещё раз.'},{status:503});}}
export async function POST(r:Request){try{const u=await getSessionUser(r);if(!u)return Response.json({error:'Войдите в профиль'},{status:401});const b=await r.json(),db=getD1(),scope=scopeFor(u.discord_id),now=Date.now();const {config,raw}=await communityConfig(scope);let stmts:D1PreparedStatement[]=[],payload:any={},action=b.action,target=u.discord_id;
 if(action==='config'){
 if(!(await hasAdminAccess(u.discord_id)))return Response.json({error:'Нет доступа'},{status:403});validate(b.config);if(b.revision!==raw)return Response.json({error:'Настройки изменились. Обновите страницу перед сохранением.'},{status:409});stmts=[configGuard(scope,raw),db.prepare('INSERT INTO site_settings(key,value,updated_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind('community:'+scope,JSON.stringify(b.config),now)];payload={activeSeason:b.config.activeSeason,sets:b.config.sets.length,events:b.config.events.length};target='community:'+scope;
 }else if(action==='lock'){
 if(typeof b.locked!=='boolean'||(!pool.some(p=>p[0]===b.slug)&&!uniqueCards.includes(b.slug)))throw Error('Неверная карточка');if(b.locked)stmts=[db.prepare('INSERT OR IGNORE INTO card_locks(user_id,card_slug) SELECT user_id,card_slug FROM user_cards WHERE user_id=? AND card_slug=? AND count>0').bind(u.discord_id,b.slug)];else stmts=[db.prepare('DELETE FROM card_locks WHERE user_id=? AND card_slug=?').bind(u.discord_id,b.slug)];payload={cardSlug:b.slug,locked:b.locked};
 }else if(action==='recycle'){
 if(!Array.isArray(b.items)||!b.items.length||b.items.length>50||new Set(b.items.map((x:any)=>x.slug)).size!==b.items.length)throw Error('Выберите повторки');let total=0;for(const item of b.items){const card=pool.find(c=>c[0]===item.slug);if(!card||!Number.isInteger(item.count)||item.count<1||item.count>10000)throw Error('Неверное количество');total+=salvage[card[1]]*item.count;stmts.push(db.prepare('UPDATE user_cards SET count=count-?,updated_at=? WHERE user_id=? AND card_slug=? AND count>? AND NOT EXISTS (SELECT 1 FROM card_locks l WHERE l.user_id=user_cards.user_id AND l.card_slug=user_cards.card_slug)').bind(item.count,now,u.discord_id,item.slug,item.count));stmts.push(db.prepare("INSERT INTO operations(id,user_id,action,result,valid,created_at) VALUES (?,?,'recycle.guard','{}',changes(),?)").bind(crypto.randomUUID(),u.discord_id,now));}stmts.push(db.prepare('UPDATE users SET fragments=fragments+? WHERE discord_id=?').bind(total,u.discord_id));payload={items:b.items,fragmentsAdded:total};
 }else if(action==='set_claim'){
 const set=config.sets.find((s:any)=>s.id===b.setId);if(!set||set.rewardKind==='none')throw Error('Награда ещё не определена');stmts=[configGuard(scope,raw),db.prepare("INSERT INTO operations(id,user_id,action,result,valid,created_at) SELECT ?,?,'set.guard','{}',CASE WHEN (SELECT COUNT(*) FROM user_cards WHERE user_id=? AND count>0 AND card_slug IN (SELECT value FROM json_each(?)))=? THEN 1 ELSE 0 END,?").bind(crypto.randomUUID(),u.discord_id,u.discord_id,JSON.stringify(set.cards),set.cards.length,now),db.prepare('INSERT INTO collection_claims(user_id,set_id,reward,created_at) VALUES (?,?,?,?)').bind(u.discord_id,set.id,JSON.stringify({kind:set.rewardKind,amount:set.rewardAmount,item:set.rewardItem}),now)];if(set.rewardKind==='cosmetic')stmts.push(db.prepare('INSERT OR IGNORE INTO user_cosmetics(user_id,item_id,created_at) VALUES (?,?,?)').bind(u.discord_id,set.rewardItem,now));else stmts.push(db.prepare(set.rewardKind==='coupons'?'UPDATE users SET tokens=tokens+? WHERE discord_id=?':'UPDATE users SET fragments=fragments+? WHERE discord_id=?').bind(set.rewardAmount,u.discord_id));payload={setId:set.id,kind:set.rewardKind,amount:set.rewardAmount,item:set.rewardItem};
 }else if(action==='event_enter'){
 const event=config.events.find((e:any)=>e.id===b.eventId&&e.open);if(!event||typeof b.evidence!=='string'||!b.evidence.trim()||b.evidence.length>1000)throw Error('Добавьте подтверждение участия в открытом событии');stmts=[configGuard(scope,raw),db.prepare("INSERT INTO event_entries(id,user_id,scope,event_id,evidence,status,reward,created_at) VALUES (?,?,?,?,?,'pending',?,?)").bind(crypto.randomUUID(),u.discord_id,scope,event.id,b.evidence.trim(),event.coupons,now)];payload={eventId:event.id,coupons:event.coupons};
 }else if(action==='event_review'){
 if(!(await hasAdminAccess(u.discord_id)))return Response.json({error:'Нет доступа'},{status:403});if(!['approved','rejected'].includes(b.status))throw Error('Неверный статус');const entry=await db.prepare('SELECT * FROM event_entries WHERE id=? AND scope=?').bind(b.entryId,scope).first<any>();if(!entry)throw Error('Заявка не найдена');target=entry.user_id;stmts=[db.prepare("UPDATE event_entries SET status=? WHERE id=? AND status='pending'").bind(b.status,b.entryId),db.prepare("INSERT INTO operations(id,user_id,action,result,valid,created_at) VALUES (?,?,'event.review','{}',changes(),?)").bind('event:'+b.entryId,u.discord_id,now)];if(b.status==='approved')stmts.push(db.prepare('UPDATE users SET tokens=tokens+? WHERE discord_id=?').bind(entry.reward,target));payload={eventId:entry.event_id,status:b.status,coupons:b.status==='approved'?entry.reward:0};
 }else throw Error('Неизвестное действие');
 if(['recycle','set_claim','event_enter'].includes(action)){if(typeof b.requestId!=='string'||! /^[a-f0-9-]{36}$/.test(b.requestId))throw Error('Нужен код операции');const op=u.discord_id+':community:'+b.requestId;const prior=await db.prepare('SELECT id FROM operations WHERE id=?').bind(op).first();if(prior)return Response.json({ok:true,profile:await profilePayload(u.discord_id)});stmts.unshift(db.prepare('INSERT INTO operations(id,user_id,action,result,valid,created_at) VALUES (?,?,?,?,1,?)').bind(op,u.discord_id,action,JSON.stringify(payload),now));}
 stmts.push(db.prepare('INSERT INTO audit_log(actor_id,action,target_id,payload,created_at) VALUES (?,?,?,?,?)').bind(u.discord_id,action,target,JSON.stringify(payload),now));try{await db.batch(stmts);}catch{return Response.json({error:'Данные изменились или действие уже выполнено. Обновите список; повторного списания нет.'},{status:409});}return Response.json({ok:true,profile:await profilePayload(u.discord_id)});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'Не удалось сохранить'},{status:400});}}
