'use client';
import {tr} from "@/lib/i18n";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {cosmetics} from '@/lib/cosmetics';
import {rarityNames,salvage,products,pool} from '@/lib/economy';
type Card={slug:string;name:string;image:string;rarity:string};
const actionNames:Record<string,string>={'prize.request':'Запрос получения приза',open_pack:'Открытие тайника',dismantle:'Переработка карточки',recycle:'Переработка повторок',purchase:'Покупка приза','cosmetic.purchase':'Покупка оформления',lock:'Защита карточки',set_claim:'Награда за комплект',event_enter:'Участие в событии',event_review:'Проверка участия','order.processing':'Заявка в обработке','order.fulfilled':'Приз выдан','order.refunded':'Возврат жетонов','order.cancelled':'Заявка отменена',config:'Настройки сообщества','admin.grant':'Выдача награды','referral.verified':'Приглашение подтверждено'};
const statuses:Record<string,string>={pending:'На проверке',approved:'Подтверждено',rejected:'Отклонено'};
const backdrops=[['/cosmetics/vault.webp','Подземный зал'],['/cosmetics/banner-1.webp','Реактор'],['/cosmetics/banner-2.webp','Зимний периметр'],['/cosmetics/banner-3.webp','Багровый шторм'],['/cosmetics/banner-4.webp','Бункер']];
export function CommunityHub({mode,account,cards,onAccount,onSeason}:{mode:'collection'|'recycle'|'history'|'events'|'seasons'|'admin';account:any;cards:Card[];onAccount:(a:any)=>void;onSeason?:()=>void}){
 const [historyQuery,setHistoryQuery]=useState('');
 const [data,setData]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[chosen,setChosen]=useState<Record<string,number>>({}),[confirm,setConfirm]=useState(false),[evidence,setEvidence]=useState<Record<string,string>>({}),[preview,setPreview]=useState<any>(null),[tab,setTab]=useState('seasons');
 async function load(){try{const r=await fetch('/api/community'+((mode==='admin'||mode==='history')?'?admin=1&q='+encodeURIComponent(historyQuery):''));const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setMessage(e instanceof Error?e.message:'Ошибка загрузки');}}
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener('s27-favorites-changed',refresh);return()=>window.removeEventListener('s27-favorites-changed',refresh);},[account?.discord_id,mode]);
 async function act(body:any){if(busy)return;setBusy(true);setMessage('');try{const r=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,requestId:crypto.randomUUID()})});const d=await r.json();if(!r.ok)throw Error(d.error);if(d.profile)onAccount(d.profile);await load();setChosen({});setConfirm(false);window.dispatchEvent(new Event('s27-community-changed'));setMessage('Сохранено.');}catch(e){setMessage(e instanceof Error?e.message:'Ошибка');}finally{setBusy(false);}}
 if(!data)return <section className="panel community-panel"><p>{tr(message||'Загружаем архив…')}</p><Button onClick={load}>{tr("ОБНОВИТЬ")}</Button></section>;
 const owned:Record<string,number>=Object.fromEntries((account?.cards||[]).map((x:any)=>[x.card_slug,x.count]));
 const total=Object.entries(chosen).reduce((n,[slug,count])=>n+count*(salvage[rarityNames.indexOf(cards.find(c=>c.slug===slug)?.rarity as any)]||0),0);
 const reward=(s:any)=>s.rewardKind==='none'?'НАГРАДА ЕЩЁ НЕ ОПРЕДЕЛЕНА':s.rewardKind==='cosmetic'?(cosmetics.find(c=>c.id===s.rewardItem)?.name||'Украшение'):`${s.rewardAmount} ${s.rewardKind==='coupons'?'купонов':'жетонов'}`;
 const cardName=(slug:string)=>cards.find(c=>c.slug===slug)?.name||'Засекречено';
 function edit(group:string,index:number,key:string,value:any){setData((d:any)=>({...d,config:{...d.config,[group]:d.config[group].map((x:any,i:number)=>i===index?{...x,[key]:value}:x)}}));}
 function add(group:string){const id=crypto.randomUUID().slice(0,8);const item=group==='seasons'?{id,name:'Новый сезон',description:'',status:'draft',accent:'#d6a548',image:'/cosmetics/vault.webp',cards:[]}:group==='sets'?{id,name:'Новый комплект',cards:[],rewardKind:'none',rewardAmount:0,rewardItem:''}:{id,name:'Новое событие',description:'',open:false,coupons:1};setData((d:any)=>({...d,config:{...d.config,[group]:[...d.config[group],item]}}));}
 async function moreHistory(){const last=data.history.at(-1)?.id;if(!last)return;setBusy(true);try{const r=await fetch('/api/community?before='+last+((mode==='admin'||mode==='history')?'&admin=1&q='+encodeURIComponent(historyQuery):''));const d=await r.json();if(!r.ok)throw Error(d.error);setData((p:any)=>({...p,history:[...p.history,...d.history]}));if(!d.history.length)setMessage('Это вся история.');}catch{setMessage('Не удалось загрузить историю.');}finally{setBusy(false);}}
 function history(){return <section className="community-panel panel"><h2>{tr("ИСТОРИЯ ОПЕРАЦИЙ")}</h2><form className="history-search" onSubmit={e=>{e.preventDefault();void load();}}><input aria-label={tr("Поиск по нику, @username или Discord ID")} placeholder={tr("Поиск по нику, @username или Discord ID")} value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)}/><Button type="submit">{tr("НАЙТИ")}</Button></form>{tr(!data.history.length&&<p>{tr("Операции появятся после первого действия.")}</p>)}<div className="activity-list">{tr(data.history.map((h:any)=>{let p:any={};try{p=JSON.parse(h.payload);}catch{}return <article key={h.id}><time>{tr(new Date(h.created_at).toLocaleString('ru-RU'))}</time><b>{tr(actionNames[h.action]||h.action)}</b>{tr(account?.is_admin&&<small>@{h.username||h.target_id||'system'} · {h.display_name||''} · {h.actor_id}</small>)}<p>{tr(p.results?.map(cardName).join(' · '))}{tr(p.cardSlug&&cardName(p.cardSlug))}{tr(p.items?.map((x:any)=>`${cardName(x.slug)} ×${x.count}`).join(' · '))}{tr(p.name||'')}{tr(p.itemId&&(cosmetics.find(c=>c.id===p.itemId)?.name||p.itemId))}{tr(p.reason&&` · ${p.reason}`)}{tr(p.kind&&` · ${p.kind==='coupons'?'Купоны':p.kind==='tokens'?'Жетоны':p.kind==='card'?'Карточки':'Оформление'}: ${p.amount||''}`)}{tr(p.kind==='card'&&p.card&&cardName(p.card))}{tr(p.couponsSpent&&` · −${p.couponsSpent} купонов`)}{tr(p.fragmentsSpent&&` · −${p.fragmentsSpent} жетонов`)}{tr(p.fragmentsAdded>0&&` · +${p.fragmentsAdded} жетонов`)}{tr(p.price&&` · ${p.price} жетонов`)}{tr(p.coupons>0&&` · ${p.coupons} купонов`)}{tr(p.locked!==undefined&&(p.locked?' · Закреплена':' · Защита снята'))}{tr(p.order&&` · Заявка ${p.order.slice(0,8)}`)}{tr(p.setId&&` · ${data.config.sets.find((s:any)=>s.id===p.setId)?.name||p.setId}`)}{tr(p.eventId&&` · ${data.config.events.find((s:any)=>s.id===p.eventId)?.name||p.eventId}`)}</p></article>;}))}</div>{tr(data.history.length>=50&&<Button variant="outline" disabled={busy} onClick={moreHistory}>{tr("ПОКАЗАТЬ РАНЬШЕ")}</Button>)}</section>;}
 return <div className="community-hub">{tr(message&&<p role="status" className="hub-message">{tr(message)}</p>)}
 {tr((mode==='collection'||mode==='recycle')&&<><section className="community-panel panel" hidden={mode==='recycle'}><h2>{tr("КОМПЛЕКТЫ")}</h2><div className="set-grid">{tr(data.config.sets.map((s:any)=>{const count=s.cards.filter((x:string)=>owned[x]>0).length,claimed=data.claims.some((x:any)=>x.set_id===s.id);return <article key={s.id}><h3>{tr(s.name)}</h3><b>{tr(count)} / {tr(s.cards.length)}</b><progress max={s.cards.length} value={count}/><p>{tr(reward(s))}</p><div className="set-cards">{tr(s.cards.map((x:string)=><span key={x} className={owned[x]?'found':''}>{tr(owned[x]?'✓ ':'')}{tr(cardName(x))}</span>))}</div><Button disabled={busy||claimed||count!==s.cards.length||s.rewardKind==='none'||!account} onClick={()=>act({action:'set_claim',setId:s.id})}>{tr(claimed?'ПОЛУЧЕНО':s.rewardKind==='none'?'НАГРАДА ПОЗЖЕ':'ПОЛУЧИТЬ НАГРАДУ')}</Button></article>;}))}</div></section>
 {tr(account&&<section className="community-panel panel"><h2>{tr("ЗАЩИТА И ПЕРЕРАБОТКА")}</h2><Button variant="outline" disabled={busy||!cards.some(c=>pool.some(p=>p[0]===c.slug)&&owned[c.slug]>1&&!data.locks.includes(c.slug))} onClick={()=>{setChosen(Object.fromEntries(cards.filter(c=>pool.some(p=>p[0]===c.slug)&&owned[c.slug]>1&&!data.locks.includes(c.slug)).map(c=>[c.slug,owned[c.slug]-1])));setConfirm(true);}}>{tr("ПЕРЕРАБОТАТЬ ВСЕ ПОВТОРКИ")}</Button><p>{tr("Закреплённые карточки и последняя копия защищены. Выбери число лишних копий.")}</p><div className="recycle-grid">{tr(cards.filter(c=>pool.some(p=>p[0]===c.slug)&&owned[c.slug]>0).map(c=>{const locked=data.locks.includes(c.slug);return <article key={c.slug}><img src={c.image} alt={tr(c.name)}/><div><b>{tr(c.name)}</b><small>{tr("Копий: ")}{tr(owned[c.slug])}</small><Button variant="outline" disabled={busy} aria-pressed={locked} onClick={()=>act({action:'lock',slug:c.slug,locked:!locked})}>{tr(locked?'ЗАКРЕПЛЕНА · СНЯТЬ':'ЗАКРЕПИТЬ')}</Button><label>{tr("В переработку")}<input type="number" min={0} max={Math.max(0,owned[c.slug]-1)} disabled={locked||owned[c.slug]<2} value={chosen[c.slug]||0} onChange={e=>setChosen({...chosen,[c.slug]:Math.min(owned[c.slug]-1,Math.max(0,Math.floor(Number(e.target.value)||0)))})}/></label></div></article>;}))}</div><Button disabled={busy||total===0} onClick={()=>setConfirm(true)}>{tr("ПЕРЕРАБОТАТЬ · +")}{tr(total)} {tr(" ЖЕТОНОВ")}</Button></section>)}
 <Dialog open={confirm} onOpenChange={setConfirm}><DialogContent className="system-dialog"><DialogTitle>{tr("ПЕРЕРАБОТАТЬ ПОВТОРКИ?")}</DialogTitle><DialogDescription>{tr("Выбранные копии исчезнут из коллекции. Последняя копия останется.")}</DialogDescription>{tr(Object.entries(chosen).filter(([,n])=>n>0).map(([s,n])=><p key={s}>{tr(cardName(s))} ×{tr(n)}</p>))}<b>{tr("Ты получишь ")}{tr(total)} {tr(" жетонов Зоны.")}</b><Button disabled={busy} onClick={()=>act({action:'recycle',items:Object.entries(chosen).filter(([,count])=>count>0).map(([slug,count])=>({slug,count}))})}>{tr("ПОДТВЕРДИТЬ")}</Button><Button variant="outline" onClick={()=>setConfirm(false)}>{tr("НАЗАД")}</Button></DialogContent></Dialog></>)}
 {tr(mode==='history'&&account?.is_admin&&history())}
 {tr(mode==='events'&&<section className="community-panel panel"><h2>{tr("СОБЫТИЯ СООБЩЕСТВА")}</h2><p>{tr("Участвуй в серверных событиях и получай купоны после проверки администрацией.")}</p>{tr(!data.config.events.length&&<p>{tr("События ещё не объявлены. Они появятся здесь с условиями участия и наградой.")}</p>)}<div className="event-grid">{tr(data.config.events.map((e:any)=>{const entry=data.entries.find((x:any)=>x.event_id===e.id);return <article key={e.id}><small>{tr(e.open?'ПРИЁМ УЧАСТНИКОВ':'ЗАКРЫТО')}</small><h3>{tr(e.name)}</h3><p>{tr(e.description)}</p><b>{tr(e.coupons)} {tr(" купонов")}</b>{tr(entry?<p>{tr(entry.status==='pending'?'Подтверждение на проверке':entry.status==='approved'?'Участие подтверждено · купоны начислены':'Участие не подтверждено. Обратись к администрации.')}</p>:e.open&&account?<><label>{tr("Ссылка на результат или описание участия")}<textarea maxLength={1000} value={evidence[e.id]||''} onChange={x=>setEvidence({...evidence,[e.id]:x.target.value})}/></label><Button disabled={busy||!evidence[e.id]?.trim()} onClick={()=>act({action:'event_enter',eventId:e.id,evidence:evidence[e.id]})}>{tr("ОТПРАВИТЬ НА ПРОВЕРКУ")}</Button></>:!account&&<p>{tr("Войди в профиль, чтобы участвовать.")}</p>)}</article>;}))}</div></section>)}
 {tr(mode==='seasons'&&<section className="community-panel panel"><h2>{tr("СЕЗОННЫЙ АРХИВ")}</h2><p>{tr("Сезоны меняются. Карточки, оформление и полученные награды остаются в твоём профиле.")}</p><div className="season-library">{tr(data.config.seasons.map((s:any)=><article key={s.id} style={{borderColor:s.accent,backgroundImage:`linear-gradient(#05090966,#050909ef),url('${s.image}')`}}><small>{tr(s.status==='active'?'АКТИВНЫЙ СЕЗОН':'АРХИВ')}</small><h3>{tr(s.name)}</h3><p>{tr(s.description)}</p><b>{tr("Собрано ")}{tr(s.cards.filter((x:string)=>owned[x]>0).length)} / {tr(s.cards.length)}</b><Button variant="outline" onClick={()=>setPreview(s)}>{tr("ПОСМОТРЕТЬ КОЛЛЕКЦИЮ")}</Button>{tr(s.status==='active'&&<Button onClick={onSeason}>{tr("К ТАЙНИКАМ")}</Button>)}</article>))}</div></section>)}
 {tr(mode==='admin'&&<><section className="community-panel panel"><h2>{tr("СЕЗОНЫ, КОМПЛЕКТЫ И СОБЫТИЯ")}</h2><p>{tr("Неизвестные награды оставь выключенными. Смена сезона сохраняет все покупки и коллекции.")}</p><div className="cosmetic-categories">{tr([['seasons','Сезоны'],['sets','Комплекты'],['events','События'],['products','Призы']].map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{tr(name)}</button>))}</div>
 <div className="community-editor">{tr(data.config[tab].map((x:any,i:number)=><article key={x.id}><small>{tr("КОД: ")}{tr(x.id)}</small>{tr(tab==='products'?<h3>{tr(products.find(p=>p.id===x.id)?.name)}</h3>:<label>{tr("Название")}<input maxLength={100} value={x.name} onChange={e=>edit(tab,i,'name',e.target.value)}/></label>)}
 {tr(tab==='seasons'&&<><label>{tr("Описание")}<textarea maxLength={1000} value={x.description} onChange={e=>edit(tab,i,'description',e.target.value)}/></label><label>{tr("Статус")}<select value={x.status} onChange={e=>{const v=e.target.value;setData((d:any)=>({...d,config:{...d.config,activeSeason:v==='active'?x.id:d.config.activeSeason,seasons:d.config.seasons.map((s:any,j:number)=>j===i?{...s,status:v}:v==='active'&&s.status==='active'?{...s,status:'archived'}:s)}}));}}><option value="draft">{tr("Черновик")}</option><option value="active">{tr("Активный")}</option><option value="archived">{tr("Архив")}</option></select></label><label>{tr("Акцент")}<input type="color" value={x.accent} onChange={e=>edit(tab,i,'accent',e.target.value)}/></label><label>{tr("Фон")}<select value={x.image} onChange={e=>edit(tab,i,'image',e.target.value)}>{tr(backdrops.map(([path,label])=><option key={path} value={path}>{tr(label)}</option>))}</select></label><Button variant="outline" onClick={()=>setPreview(x)}>{tr("ПРЕДПРОСМОТР")}</Button></>)}
 {tr((tab==='seasons'||tab==='sets')&&<fieldset><legend>{tr("Карточки")}</legend><div className="set-card-picker">{tr(cards.map(c=><label key={c.slug}><input type="checkbox" checked={x.cards.includes(c.slug)} onChange={e=>edit(tab,i,'cards',e.target.checked?[...x.cards,c.slug]:x.cards.filter((s:string)=>s!==c.slug))}/>{tr(c.name)}</label>))}</div></fieldset>)}
 {tr(tab==='sets'&&<><label>{tr("Награда")}<select value={x.rewardKind} onChange={e=>{edit(tab,i,'rewardKind',e.target.value);if(e.target.value!=='none')edit(tab,i,'rewardAmount',Math.max(1,x.rewardAmount));}}><option value="none">{tr("Не определена · выдача выключена")}</option><option value="coupons">{tr("Купоны")}</option><option value="tokens">{tr("Жетоны")}</option><option value="cosmetic">{tr("Оформление")}</option></select></label>{tr(x.rewardKind==='cosmetic'?<label>{tr("Предмет")}<select value={x.rewardItem} onChange={e=>edit(tab,i,'rewardItem',e.target.value)}><option value="">{tr("Выбрать")}</option>{tr(cosmetics.map(c=><option key={c.id} value={c.id}>{tr(c.name)}</option>))}</select></label>:x.rewardKind!=='none'&&<label>{tr("Количество")}<input type="number" min={1} max={10000} value={x.rewardAmount} onChange={e=>edit(tab,i,'rewardAmount',Number(e.target.value))}/></label>)}</>)}
 {tr(tab==='events'&&<><label>{tr("Условия участия")}<textarea maxLength={2000} value={x.description} onChange={e=>edit(tab,i,'description',e.target.value)}/></label><label>{tr("Купонов за участие")}<input type="number" min={1} max={100} value={x.coupons} onChange={e=>edit(tab,i,'coupons',Number(e.target.value))}/></label><label><input type="checkbox" checked={x.open} onChange={e=>edit(tab,i,'open',e.target.checked)}/>{tr("Принимать участников")}</label></>)}
 {tr(tab==='products'&&<><label><input type="checkbox" checked={x.available} onChange={e=>edit(tab,i,'available',e.target.checked)}/>{tr("Доступен для заказа")}</label><label>{tr("Условия, регион и срок выдачи")}<textarea maxLength={1000} value={x.conditions} onChange={e=>edit(tab,i,'conditions',e.target.value)}/></label></>)}
 </article>))}</div>{tr(tab!=='products'&&<Button variant="outline" onClick={()=>add(tab)}>{tr("ДОБАВИТЬ")}</Button>)}<Button disabled={busy} onClick={()=>act({action:'config',config:data.config,revision:data.revision})}>{tr("СОХРАНИТЬ НАСТРОЙКИ")}</Button></section>
 <section className="community-panel panel"><h2>{tr("ПОДТВЕРЖДЕНИЯ УЧАСТИЯ")}</h2>{tr(data.entries.length?data.entries.map((e:any)=><article className="event-review" key={e.id}><h3>{tr(data.config.events.find((x:any)=>x.id===e.event_id)?.name||e.event_id)}</h3><b>{tr(e.display_name)} · {tr(e.reward)} {tr(" купонов")}</b><p>{tr(e.evidence)}</p><small>{tr(statuses[e.status])}</small>{tr(e.status==='pending'&&<div><Button disabled={busy} onClick={()=>act({action:'event_review',entryId:e.id,status:'approved'})}>{tr("ПОДТВЕРДИТЬ")}</Button><Button variant="outline" disabled={busy} onClick={()=>act({action:'event_review',entryId:e.id,status:'rejected'})}>{tr("ОТКЛОНИТЬ")}</Button></div>)}</article>):<p>{tr("Заявок пока нет.")}</p>)}</section>{tr(history())}</>)}
 <Dialog open={!!preview} onOpenChange={v=>!v&&setPreview(null)}><DialogContent className="system-dialog season-preview"><DialogTitle>{tr(preview?.name)}</DialogTitle><DialogDescription>{tr(preview?.description)}</DialogDescription>{tr(preview&&<><div className="season-preview-art" style={{backgroundImage:`url('${preview.image}')`,borderColor:preview.accent}}/><div className="preview-card-grid">{tr(preview.cards.map((s:string)=>{const c=cards.find(c=>c.slug===s);return c&&<article key={s}><img src={c.image} alt={tr(c.name)}/><b>{tr(c.name)}</b><small>{tr(owned[s]?'В коллекции':'Не получена')}</small></article>;}))}</div></>)}</DialogContent></Dialog>
 </div>;
}
