'use client';
import {tr} from "@/lib/i18n";
import {useEffect,useState} from 'react';import {Button} from '@/components/ui/button';
export function InventoryAdmin({cards,onAccount}:{cards:Array<{slug:string;name:string;rarity:string}>;onAccount:(a:any)=>void}){
 const [data,setData]=useState<any>({members:[],audit:[]}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[search,setSearch]=useState('');const [form,setForm]=useState({target:'',kind:'coupons',amount:1,cardSlug:'shinigami',reason:''});
 async function load(){const r=await fetch('/api/inventory-admin?q='+encodeURIComponent(search));const d=await r.json();if(r.ok)setData(d);else setMessage(d.error);}
 useEffect(()=>{const t=setTimeout(()=>void load().catch(()=>setMessage('Не удалось загрузить участников')),250);const poll=setInterval(()=>void load(),15000);return()=>{clearTimeout(t);clearInterval(poll);};},[search]);
 async function grant(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);try{const r=await fetch('/api/inventory-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,requestId:crypto.randomUUID()})});const d=await r.json();if(!r.ok)throw Error(d.error);if(d.profile)onAccount(d.profile);setMessage('Выдача сохранена. Участник увидит её после обновления профиля.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Ошибка');}finally{setBusy(false);}}
 return <section className="inventory-admin panel"><h2>{tr("ВЫДАЧА НАГРАД")}</h2><p>{tr("Каждая операция сохраняется с получателем и причиной.")}</p>{tr(message&&<p role="status" className="hub-message">{tr(message)}</p>)}<label>{tr("Поиск по @нику или имени")}<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="@wladekk3" /></label><form onSubmit={grant}><label>{tr("Участник")}<select required value={form.target} onChange={e=>setForm({...form,target:e.target.value})}><option value="">{tr("Выберите участника")}</option>{tr(data.members.map((u:any)=><option value={u.discord_id} key={u.discord_id}>@{u.username} · {u.display_name}</option>))}</select></label><label>{tr("Награда")}<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value,amount:1})}><option value="coupons">{tr("Купоны")}</option><option value="tokens">{tr("Жетоны Зоны")}</option><option value="card">{tr("Карточка")}</option></select></label>{tr(form.kind==='card'&&<label>{tr("Карточка")}<select value={form.cardSlug} onChange={e=>setForm({...form,cardSlug:e.target.value})}>{tr(cards.map(c=><option value={c.slug} key={c.slug}>{tr(c.name)} · {tr(c.rarity)} · {tr(c.slug)}</option>))}</select></label>)}<label>{tr("Количество")}<input type="number" min={1} max={form.kind==='card'?100:100000} value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></label><label>{tr("Причина")}<input required maxLength={300} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><Button disabled={busy} type="submit">{tr(busy?'ВЫДАЁМ…':'ВЫДАТЬ НАГРАДУ')}</Button></form>
 <div className="admin-table"><table><thead><tr><th>{tr("Участник")}</th><th>{tr("Купоны")}</th><th>{tr("Жетоны")}</th></tr></thead><tbody>{tr(data.members.map((u:any)=><tr key={u.discord_id}><td><b>@{u.username}</b><br/>{u.display_name}<br/><small>{tr(u.registered_at?"Зарегистрирован на сайте":"Синхронизирован ботом")}</small></td><td>{tr(u.tokens)}</td><td>{tr(u.fragments)}</td></tr>))}</tbody></table></div><h3>{tr("ЖУРНАЛ ДЕЙСТВИЙ")}</h3><div className="grant-log">{tr(data.audit.map((a:any,i:number)=><p key={i}><time>{tr(new Date(a.created_at).toLocaleString('ru-RU'))}</time><b>{tr(a.action)} → {tr(a.target_id)}</b><span>{tr(a.payload)}</span></p>))}</div></section>;
}
