'use client';
import {useEffect,useState} from 'react';
import {Trophy,Coins,PackageOpen,Users,Layers,RefreshCw,Search} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {useLanguage} from './language';
export function Leaderboard({admin=false,compact=false,onOpen}:{admin?:boolean;compact?:boolean;onOpen?:()=>void}){
 const {locale}=useLanguage(),en=locale==='en';const [metric,setMetric]=useState('tokens'),[query,setQuery]=useState(''),[members,setMembers]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[saving,setSaving]=useState('');
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{setLoading(true);setError('');fetch(`/api/leaderboard?metric=${metric}${admin?'&admin=1&q='+encodeURIComponent(query):''}`,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{setMembers(d.members);setLoading(false);}).catch(()=>{if(!controller.signal.aborted){setLoading(false);setError(en?'Could not load leaders. Please retry.':'Не удалось загрузить рейтинг. Повторите.');}});},admin?250:0);return()=>{clearTimeout(timer);controller.abort();};},[metric,query,admin,refresh,en]);
 async function toggle(row:any){setSaving(row.discord_id);setError('');try{const r=await fetch('/api/leaderboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:row.discord_id,hidden:!row.hidden})});if(!r.ok)throw Error();setRefresh(v=>v+1);}catch{setError(en?'Could not save. Please retry.':'Не удалось сохранить. Повторите.');}finally{setSaving('');}}
 const categories=[['tokens',en?'Tokens':'Жетоны',Coins],['packs',en?'Caches':'Тайники',PackageOpen],['invites',en?'Invites':'Приглашения',Users],['cards',en?'Collection':'Коллекция',Layers]] as const;
 return <section className="leaderboard-panel"><header><div><Trophy/><h2>{admin?(en?'LEADERBOARD VISIBILITY':'ВИДИМОСТЬ В РЕЙТИНГЕ'):(en?'ZONE LEADERS':'ЛИДЕРЫ ЗОНЫ')}</h2></div><button onClick={()=>setRefresh(v=>v+1)} aria-label={en?'Refresh leaderboard':'Обновить рейтинг'} disabled={loading}><RefreshCw/></button></header><p>{admin?(en?'Curators and managers are excluded automatically. Hide or show other registered members.':'Кураторы и менеджеры исключены автоматически. Здесь можно скрыть или показать остальных зарегистрированных участников.'):(en?'Current tokens · opened caches · verified invites · distinct owned cards. Staff accounts are excluded.':'Текущие жетоны · открытые тайники · проверенные приглашения · разные карты в коллекции. Аккаунты администрации не участвуют.')}</p><div className="leaderboard-tabs">{categories.map(([id,label,Icon])=><button key={id} aria-pressed={metric===id} onClick={()=>setMetric(id)}><Icon/>{label}</button>)}</div>{admin&&<label className="leaderboard-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={en?'Search @username or name':'Найти по @нику или имени'} aria-label={en?'Find member':'Найти участника'}/></label>}{error&&<p role="alert">{error}</p>}{loading?<p role="status">{en?'Loading…':'Загрузка…'}</p>:members.length?<ol className="leaderboard-list">{members.slice(0,compact?5:50).map((m,i)=><li key={m.discord_id||m.username}><span className="leader-place">{i+1}</span><div className="leader-person"><strong>{admin?m.display_name:m.displayName}</strong><span>@{m.username}</span></div><b>{Number(admin?m[metric]:m.score).toLocaleString(locale)}</b>{admin&&(m.staff?<span className="leader-staff">{en?'Staff · excluded':'Администрация · исключён'}</span>:<Button variant="outline" disabled={!!saving} onClick={()=>toggle(m)}>{m.hidden?(en?'Show':'Показать'):(en?'Hide':'Скрыть')}</Button>)}</li>)}</ol>:<p>{en?'No participants yet.':'Пока нет участников.'}</p>}{compact&&onOpen&&<Button variant="outline" onClick={onOpen}>{en?'ALL LEADERS':'ВЕСЬ РЕЙТИНГ'}</Button>}</section>;
}
