'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {LanguageSwitch,useLanguage} from './language';

const WIDTH=600,HEIGHT=700,PADDLE_W=112,PADDLE_H=16,BALL_R=8,LEVELS=5;
const glyphs:Record<string,string[]>={
 N:['#..#','##.#','#.##','#..#','#..#'],E:['####','#...','###.','#...','####'],S:['####','#...','####','...#','####'],
 '2':['###.','...#','###.','#...','####'],'7':['####','...#','..#.','.#..','.#..']
};
function wordPattern(text:string){const chars=[...text];return Array.from({length:5},(_,row)=>chars.map(c=>c===' '?'..':glyphs[c][row]).join('..'));}
const patterns=[
 wordPattern('NE'),wordPattern('S27'),
 ['.....###.....','...#######...','..###...###..','###..###..###','##..#####..##','....#####....','...#######...','..###...###..'],
 ['......#......','....#####....','..#########..','#############','..#########..','....#####....','......#......'],
 wordPattern('NE S27'),
];
const levelNames=['NE','S27','☢ RADIATION','ANOMALY','NE S27'];
type Brick={x:number;y:number;w:number;h:number;alive:boolean;label:string;hp:number};
type Game={level:number;paddle:number;ball:{x:number;y:number;vx:number;vy:number};bricks:Brick[];running:boolean;lives:number};
function makeLevel(level:number):Game{const pattern=patterns[level],cols=Math.max(...pattern.map(r=>r.length)),gap=4,cell=Math.min(31,(WIDTH-50-gap*(cols-1))/cols),total=cols*(cell+gap)-gap,left=(WIDTH-total)/2,bricks:Brick[]=[];pattern.forEach((row,y)=>[...row].forEach((mark,x)=>{if(mark!=='#')return;const strong=level>=3&&(x+y)%5===0;bricks.push({x:left+x*(cell+gap),y:72+y*(cell*.72+gap),w:cell,h:Math.max(16,cell*.72),alive:true,label:level===2?'☢':level===3?'◆':'',hp:strong?2:1})}));const speed=4.6+level*.35;return{level,paddle:(WIDTH-PADDLE_W)/2,ball:{x:WIDTH/2,y:HEIGHT-92,vx:speed*(level%2?1:-1),vy:-speed},bricks,running:false,lives:3};}

export function MaintenanceGate(){
 const{locale}=useLanguage(),canvas=useRef<HTMLCanvasElement>(null),game=useRef<Game>(makeLevel(0)),frame=useRef(0),[level,setLevel]=useState(0),[lives,setLives]=useState(3),[status,setStatus]=useState<'ready'|'playing'|'lost'|'won'|'claiming'|'reward'>('ready'),[code,setCode]=useState(''),[message,setMessage]=useState('');const en=locale==='en';
 const draw=useCallback(()=>{const c=canvas.current,g=game.current;if(!c)return;const x=c.getContext('2d');if(!x)return;const grad=x.createLinearGradient(0,0,0,HEIGHT);grad.addColorStop(0,'#0f1914');grad.addColorStop(1,'#030605');x.fillStyle=grad;x.fillRect(0,0,WIDTH,HEIGHT);x.strokeStyle='#25352d';x.globalAlpha=.38;for(let i=0;i<WIDTH;i+=30){x.beginPath();x.moveTo(i,0);x.lineTo(i,HEIGHT);x.stroke()}x.globalAlpha=1;x.textAlign='center';x.textBaseline='middle';g.bricks.forEach(b=>{if(!b.alive)return;const rare=b.hp>1;x.fillStyle=rare?'#4a311b':'#192119';x.strokeStyle=rare?'#d68b35':'#8b713e';x.lineWidth=rare?2:1;x.fillRect(b.x,b.y,b.w,b.h);x.strokeRect(b.x+.5,b.y+.5,b.w-1,b.h-1);x.fillStyle=rare?'#ffd077':'#d9c79b';x.font=`700 ${b.label.length>5?11:14}px monospace`;x.fillText(b.label,b.x+b.w/2,b.y+b.h/2)});x.shadowColor='#d9aa45';x.shadowBlur=14;x.fillStyle='#d9aa45';x.fillRect(g.paddle,HEIGHT-43,PADDLE_W,PADDLE_H);x.shadowColor='#81d7f5';x.shadowBlur=13;x.beginPath();x.arc(g.ball.x,g.ball.y,BALL_R,0,Math.PI*2);x.fillStyle='#d9f4ff';x.fill();x.shadowBlur=0;x.fillStyle='#98a598';x.font='12px monospace';x.textAlign='left';x.fillText(`NE S27 // ${String(g.level+1).padStart(2,'0')}`,18,22);x.textAlign='right';x.fillText(`♥ ${g.lives}`,WIDTH-18,22)},[]);
 const resetBall=useCallback(()=>{const g=game.current,s=4.5+g.level*.28;g.ball={x:WIDTH/2,y:HEIGHT-92,vx:s*(Math.random()>.5?1:-1),vy:-s};g.paddle=(WIDTH-PADDLE_W)/2;g.running=false;setStatus('ready');draw()},[draw]);
 const winAll=useCallback(async()=>{setStatus('claiming');setMessage('');try{const r=await fetch('/api/maintenance-reward',{method:'POST',credentials:'same-origin'}),d=await r.json();if(!r.ok)throw Error(d.error);setCode(d.code);setStatus('reward')}catch{setMessage(en?'Could not create the code. Tap retry.':'Не удалось создать код. Нажми повторить.');setStatus('won')}},[en]);
 const tick=useCallback(()=>{const g=game.current;if(!g.running)return;const b=g.ball;b.x+=b.vx;b.y+=b.vy;if(b.x<BALL_R||b.x>WIDTH-BALL_R){b.vx*=-1;b.x=Math.max(BALL_R,Math.min(WIDTH-BALL_R,b.x))}if(b.y<BALL_R+30){b.vy=Math.abs(b.vy);b.y=BALL_R+30}const py=HEIGHT-43;if(b.vy>0&&b.y+BALL_R>=py&&b.y-BALL_R<=py+PADDLE_H&&b.x>=g.paddle-5&&b.x<=g.paddle+PADDLE_W+5){const hit=(b.x-(g.paddle+PADDLE_W/2))/(PADDLE_W/2);b.vx=hit*(5.8+g.level*.3);b.vy=-Math.max(4.4,Math.abs(b.vy));b.y=py-BALL_R-1}for(const brick of g.bricks){if(!brick.alive)continue;if(b.x+BALL_R>brick.x&&b.x-BALL_R<brick.x+brick.w&&b.y+BALL_R>brick.y&&b.y-BALL_R<brick.y+brick.h){brick.hp--;if(brick.hp<=0)brick.alive=false;b.vy*=-1;break}}if(!g.bricks.some(v=>v.alive)){g.running=false;if(g.level===LEVELS-1){setStatus('won');void winAll();draw();return}game.current=makeLevel(g.level+1);setLevel(g.level+1);setLives(3);setStatus('ready');draw();return}if(b.y>HEIGHT+BALL_R){g.lives--;setLives(g.lives);if(g.lives<=0){g.running=false;setStatus('lost');draw();return}resetBall();return}draw();frame.current=requestAnimationFrame(tick)},[draw,resetBall,winAll]);
 useEffect(()=>{draw();return()=>cancelAnimationFrame(frame.current)},[draw]);
 const start=()=>{if(status==='lost'){game.current=makeLevel(level);setLives(3)}game.current.running=true;setStatus('playing');cancelAnimationFrame(frame.current);frame.current=requestAnimationFrame(tick)};
 const move=(clientX:number)=>{const rect=canvas.current?.getBoundingClientRect();if(!rect)return;game.current.paddle=Math.max(0,Math.min(WIDTH-PADDLE_W,(clientX-rect.left)/rect.width*WIDTH-PADDLE_W/2));draw()};
 const key=useCallback((e:KeyboardEvent)=>{const g=game.current;if(e.key==='ArrowLeft'||e.key==='a')g.paddle=Math.max(0,g.paddle-34);if(e.key==='ArrowRight'||e.key==='d')g.paddle=Math.min(WIDTH-PADDLE_W,g.paddle+34);draw()},[draw]);
 useEffect(()=>{addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[key]);
 const copy=async()=>{try{await navigator.clipboard.writeText(code);setMessage(en?'Code copied. Redeem it when the site reopens.':'Код скопирован. Активируй его после открытия сайта.')}catch{setMessage(code)}};
 return <main className="maintenance-screen"><header><span className="brand-emblem"><img src="/favicon.svg" alt="NE S27"/></span><b>NE S27</b><LanguageSwitch/></header><section><small>STATUS // 27</small><h1>{en?'SITE TEMPORARILY SUSPENDED':'САЙТ ВРЕМЕННО ПРИОСТАНОВЛЕН'}</h1><p>{en?'The Zone is being updated. Staff retain access. Clear all 5 Arkanoid sectors and receive a one-use code for 2 free caches. One win per maintenance period.':'В Зоне идёт обновление. Команда сохраняет доступ. Пройди 5 секторов арканоида и получи одноразовый код на 2 бесплатных тайника. Одна победа за период паузы.'}</p></section><div className="maintenance-game arkanoid"><div className="maintenance-game-head"><b>{en?'ZONE ARKANOID':'АРКАНОИД ЗОНЫ'} · {levelNames[level]}</b><span>{en?'LEVEL':'УРОВЕНЬ'} {level+1}/{LEVELS} · ♥ {lives}</span></div><canvas ref={canvas} width={WIDTH} height={HEIGHT} onPointerMove={e=>move(e.clientX)} onPointerDown={e=>{move(e.clientX);if(!game.current.running&&status!=='reward'&&status!=='claiming')start()}} aria-label={en?'NE S27 Arkanoid game field':'Игровое поле арканоида NE S27'}/><div className="arkanoid-actions">{status==='ready'&&<button onClick={start}>{en?'START SECTOR':'НАЧАТЬ СЕКТОР'}</button>}{status==='lost'&&<button onClick={start}>{en?'RETRY LEVEL':'ПОВТОРИТЬ УРОВЕНЬ'}</button>}{status==='playing'&&<span>{en?'MOVE: TOUCH, MOUSE OR ← →':'ДВИЖЕНИЕ: ПАЛЕЦ, МЫШЬ ИЛИ ← →'}</span>}{status==='claiming'&&<span>{en?'CREATING REWARD CODE…':'СОЗДАЁМ КОД НАГРАДЫ…'}</span>}{status==='won'&&<button onClick={winAll}>{en?'RETRY REWARD':'ПОВТОРИТЬ ВЫДАЧУ'}</button>}</div>{status==='reward'&&<div className="arkanoid-reward"><small>{en?'SECTOR CLEAR · REWARD':'СЕКТОР ЗАЧИЩЕН · НАГРАДА'}</small><strong>+2 {en?'CACHES':'ТАЙНИКА'}</strong><code>{code}</code><button onClick={copy}>{en?'COPY CODE':'СКОПИРОВАТЬ КОД'}</button><p>{en?'Save it and redeem it after the site reopens. This code works once.':'Сохрани и активируй код после открытия сайта. Код работает один раз.'}</p></div>}{message&&<p className="arkanoid-message" role="status">{message}</p>}</div></main>;
}
