'use client';
import {FavoriteStar} from './favorite-star';
import {FavoriteCollection} from './favorite-collection';
import {tr} from "@/lib/i18n";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {cosmetics,avatars,slotNames,type Cosmetic,type CosmeticSlot} from '@/lib/cosmetics';
import {ShieldCheck,Palette,Flame,Orbit,Sparkles,Film,MousePointer2,Eye,Check,LockKeyhole} from 'lucide-react';
import {previewSound} from '@/lib/zone-soundtrack';
import {CacheReveal} from './cache-reveal';
import {PublicProfiles} from './public-profiles';
type Card={slug:string;name:string;image:string;rarity:string;tirazh?:number|null};
function avatarFor(account:any,profile:any){return account.avatar_url||avatars[profile.avatar]||avatars.shinigami;}
function Avatar({src,frame}:{src:string;frame?:string}){return <div className="portrait-composite"><img className="portrait-face" src={src} alt={tr("Аватар участника")}/>{tr(frame&&<img className="portrait-decoration" src={frame} alt={tr("Украшение аватара")}/>)}</div>;}
export function MemberHub({account,cards,mode,onAccount,onLogin}:{account:any;cards:Card[];mode:'profile'|'shop';onAccount:(a:any)=>void;onLogin?:()=>void}){
 const [fitting,setFitting]=useState<Record<string,string>>({});
 const [data,setData]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[category,setCategory]=useState<CosmeticSlot|'all'>('all'),[preview,setPreview]=useState<Cosmetic|null>(null),[playing,setPlaying]=useState(false);
 const [form,setForm]=useState({nickname:'',bio:'',status:'На связи',avatar:'shinigami',showcase:[] as string[]});
 async function load(){if(!account){setData({profile:{equipped:'{}',showcase:'[]',avatar:'shinigami'},owned:[]});return;}try{const r=await fetch('/api/member-profile');const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setForm({...d.profile,showcase:JSON.parse(d.profile.showcase||'[]')});}catch(e){setMessage(e instanceof Error?e.message:'Ошибка загрузки');}}
 useEffect(()=>{setData(null);void load();const refresh=()=>void load();window.addEventListener('s27-profile-changed',refresh);return()=>window.removeEventListener('s27-profile-changed',refresh);},[account?.discord_id]);
 async function action(body:any){if(!account){onLogin?.();return;}if(busy)return;setBusy(true);setMessage('');try{const r=await fetch('/api/member-profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,requestId:crypto.randomUUID()})});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);onAccount(d.account);window.dispatchEvent(new CustomEvent('s27-profile-changed',{detail:{sound:body.action==='preset_apply'||body.action==='equip'&&body.slot==='sound'}}));setMessage(body.action==='wish'?'Список желаний обновлён.':body.action.startsWith('preset_')?'Образы обновлены.':body.action==='purchase'?'Покупка сохранена. Нажми «Надеть», чтобы включить украшение.':body.action==='equip'?'Оформление обновлено.':'Профиль сохранён.');if(body.action==='save')setEditing(false);}catch(e){setMessage(e instanceof Error?e.message:'Ошибка');}finally{setBusy(false);}}
 if(!data)return <div className="panel hub-loading">{tr(message||'Загружаем личное дело…')}<Button variant="outline" onClick={load}>{tr("Обновить")}</Button></div>;
 const equipped=JSON.parse(data.profile.equipped||'{}'),ownedIds=data.owned as string[];
 const ownedCards=cards.filter(c=>account?.cards.some((x:any)=>x.card_slug===c.slug&&x.count>0));
 const showcase=JSON.parse(data.profile.showcase||'[]') as string[];
 const displayed=(showcase.length?showcase.map(id=>ownedCards.find(c=>c.slug===id)).filter(Boolean):ownedCards.slice(0,3)) as Card[];
 const frame=cosmetics.find(c=>c.id===equipped.frame)?.image,banner=cosmetics.find(c=>c.id===equipped.banner)?.image,avatar=avatarFor(account||{},data.profile);
 const items=cosmetics.filter(c=>(mode==='shop'||ownedIds.includes(c.id))&&(category==='all'||c.slot===category));
 function purchaseButton(item:Cosmetic){const owned=ownedIds.includes(item.id),active=equipped[item.slot]===item.id;return <Button disabled={busy||!!account&&(!owned&&account.fragments<item.price)} onClick={()=>void action(owned?{action:'equip',slot:item.slot,itemId:active?'':item.id}:{action:'purchase',itemId:item.id})}>{tr(!account?'ВОЙТИ':owned?(active?'СНЯТЬ':'НАДЕТЬ'):account.fragments<item.price?'НЕ ХВАТАЕТ ЖЕТОНОВ':'ПРИОБРЕСТИ')}</Button>;}
 return <div className="member-hub">{tr(message&&<p role="status" className="hub-message">{tr(message)}</p>)}
 {mode==='profile'&&<PublicProfiles cards={cards}/>} 
 {tr(mode==='profile'&&account&&<>
 <section className={`discord-profile ${equipped.effect?'profile-aura '+equipped.effect:''}`}>
 <div className="discord-profile-banner" style={banner?{backgroundImage:`linear-gradient(0deg,#070d1099,transparent),url('${banner}')`}:undefined}><span>NE S27 / SHADOW OF CHERNOBYL</span></div>
 <div className="discord-profile-body"><div className="profile-portrait"><Avatar src={avatar} frame={frame}/></div>
 <div className="profile-tools"><span className="role-badge">{tr(account.is_owner?<><ShieldCheck/> {tr(" ОВНЕР")}</>:account.is_admin?<><ShieldCheck/> {tr(" АДМИНИСТРАТОР")}</>:account.is_manager?'МЕНЕДЖЕР':'УЧАСТНИК')}</span><Button type="button" onClick={()=>setEditing(true)} variant="outline">{tr("ИЗМЕНИТЬ ПРОФИЛЬ")}</Button></div>
 <h2>{tr(data.profile.nickname||account.display_name)}</h2><p className="handle">@{tr(account.username)}</p>{account.pioneer&&<p className="pioneer-badge">{tr("ПЕРВЫЕ У КОСТРА")} · №{String(account.pioneer.number).padStart(2,"0")} / 30</p>}<p className="member-status">{tr(data.profile.status)}</p>
 <div className="about-me"><h3>{tr("ОБО МНЕ")}</h3><p>{tr(data.profile.bio||'Свою историю ещё предстоит написать.')}</p></div>
 <div className="member-stats"><div><b>{tr(account.cards.reduce((n:number,c:any)=>n+c.count,0))}</b><span>{tr("карт")}</span></div><div><b>{tr(account.tokens)}</b><span>{tr("купонов")}</span></div><div><b>{tr(account.fragments)}</b><span>{tr("жетонов Зоны")}</span></div><div><b>{tr(account.pack_count)}</b><span>{tr("тайников")}</span></div></div>
 </div></section>
 <Dialog open={editing} onOpenChange={setEditing}><DialogContent className="profile-edit-dialog"><DialogTitle>{tr("ИЗМЕНИТЬ ЛИЧНОЕ ДЕЛО")}</DialogTitle><DialogDescription>{tr(account.is_test?'Тестовый профиль. После привязки Discord аватар будет приходить из Discord.':'Аватар берётся из Discord. Здесь можно изменить оформление личного дела.')}</DialogDescription><form className="profile-editor" onSubmit={e=>{e.preventDefault();void action({action:'save',...form});}}><label>{tr("Имя на сайте")}<input maxLength={40} value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})}/></label><label>{tr("Статус")}<input maxLength={80} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}/></label><label>{tr("Обо мне")}<textarea maxLength={280} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label>{tr(account.is_test&&<label>{tr("Аватар для теста")}<select value={form.avatar} onChange={e=>setForm({...form,avatar:e.target.value})}>{tr(Object.keys(avatars).map(id=><option key={id} value={id}>{tr(id.toUpperCase())}</option>))}</select></label>)}<fieldset><legend>{tr("Витрина — до 3 карт")}</legend><div className="showcase-picker">{tr(ownedCards.length?ownedCards.map(c=><label key={c.slug}><input type="checkbox" checked={form.showcase.includes(c.slug)} disabled={!form.showcase.includes(c.slug)&&form.showcase.length>=3} onChange={e=>setForm({...form,showcase:e.target.checked?[...form.showcase,c.slug]:form.showcase.filter(id=>id!==c.slug)})}/>{tr(c.name)}</label>):<p>{tr("Сначала получи карточки из тайника.")}</p>)}</div></fieldset>{tr(message&&<p role="status">{tr(message)}</p>)}<Button disabled={busy} type="submit">{tr(busy?'СОХРАНЯЕМ…':'СОХРАНИТЬ')}</Button></form></DialogContent></Dialog>
 <section className="profile-display panel"><h3>{tr("ВИТРИНА КОЛЛЕКЦИИ")}</h3><div>{tr(displayed.length?displayed.map(c=><article key={c.slug}><img src={c.image} alt={tr(c.name)}/><b>{tr(c.name)}</b><small>{tr(c.rarity)}</small></article>):<p>{tr("Первые карты появятся после открытия тайника.")}</p>)}</div></section>
 </>)}
 {tr(mode==='shop'&&<section className="atelier-hero"><div><span>{tr("СНАРЯЖЕНИЕ ДЛЯ ТВОЕГО ДОСЬЕ")}</span><h2>{tr("МАСТЕРСКАЯ")}<br/>{tr("ПЕРИМЕТРА")}</h2><p>{tr("Выбери свой след в Зоне.")}</p><b>{tr(cosmetics.length)} {tr(" предметов · покупка один раз")}</b></div></section>)}
 <section className="wardrobe panel"><div className="wardrobe-title"><Palette/><div><h2>{tr(mode==='shop'?'ВЫБЕРИ СВОЁ ОФОРМЛЕНИЕ':'МОЙ ГАРДЕРОБ')}</h2><p>{tr(mode==='shop'?'Сначала примерь. Все украшения и способы открытия сохраняются в гардеробе.':'Включай украшения или возвращай стандартный вид.')}</p></div></div>
 <div className="cosmetic-categories" role="group" aria-label={tr("Категория украшений")}><button aria-pressed={category==='all'} onClick={()=>setCategory('all')}>{tr("Все")}</button>{tr(Object.entries(slotNames).map(([slot,title])=><button key={slot} aria-pressed={category===slot} onClick={()=>setCategory(slot as CosmeticSlot)}>{tr(title)}</button>))}</div>
 <FavoriteCollection kind="product" userId={account?.discord_id} className="cosmetic-grid">{tr(items.map(item=>{const owned=ownedIds.includes(item.id),active=equipped[item.slot]===item.id;return <article key={item.id} data-favorite-id={item.id} className={'cosmetic-tile cosmetic-'+item.slot}><FavoriteStar id={item.id} kind="product" enabled={!!account}/><button className="cosmetic-preview art-preview" aria-label={tr('Примерить '+item.name)} onClick={()=>{setPlaying(false);setFitting({...equipped,[item.slot]:item.id});setPreview(item);}}>{tr(item.slot==='frame'?<Avatar src={avatar} frame={item.image}/>:item.image?<><img src={item.image} alt={tr(item.name)}/>{tr(item.slot==='reveal'&&<Film/>)}{tr(item.slot==='theme'&&<i style={{background:item.accent}}/>)}</>:<div className={'gesture-preview gesture-'+item.id} style={{color:item.accent}}>{tr(item.slot==='cursor'?<MousePointer2/>:<Sparkles/>)}<span/></div>)}<span className="try-label"><Eye/> {tr(" ПРИМЕРИТЬ")}</span></button><small>{tr(slotNames[item.slot])}{tr(active?' · НАДЕТО':'')}</small><h3>{tr(item.name)}</h3><p>{tr(item.description)}</p><b>{tr(owned?<><Check size={16}/> {tr(" КУПЛЕНО")}</>:`${item.price} ЖЕТОНОВ`)}</b>{tr(purchaseButton(item))}</article>;}))}</FavoriteCollection>
 {tr(!items.length&&<p className="wardrobe-empty">{tr("В этой категории пока нет покупок.")}</p>)}
 <p className="cosmetic-fairness"><LockKeyhole size={16}/> {tr(" Способ открытия и украшения не меняют шансы. Один тайник всегда даёт одну карту.")}</p>
 </section>
 <Dialog open={!!preview} onOpenChange={v=>{if(!v){setPreview(null);setPlaying(false);}}}><DialogContent className={playing?'cosmetic-try-dialog is-playing':'cosmetic-try-dialog'}><DialogTitle>{tr(preview?.name)}</DialogTitle><DialogDescription>{tr(preview?.description)}</DialogDescription>{tr(preview&&(playing?<><p>{tr("ПРИМЕР · КУПОНЫ НЕ СПИСЫВАЮТСЯ")}</p><CacheReveal key={preview.id} theme={preview.id} cards={[{...cards.find(c=>c.rarity==='РЕДКАЯ')!,tirazh:4}]} onDone={()=>setPlaying(false)}/></>:<><div className={"cosmetic-fitting "+(fitting.effect?"profile-aura "+fitting.effect:"")} style={{backgroundImage:`linear-gradient(0deg,#050a11cc,transparent),url('${cosmetics.find(c=>c.id===fitting.banner)?.image||'/cosmetics/banner-4.webp'}')`,borderColor:cosmetics.find(c=>c.id===fitting.theme)?.accent||preview.accent}}>{tr(preview.id==='classic-cursor'?<img className="cursor-fitting-image" src={preview.image} alt={tr("Курсор сталкера")}/>:<Avatar src={avatar} frame={cosmetics.find(c=>c.id===fitting.frame)?.image}/>)}<h3>{tr(data.profile.nickname||account?.display_name||'СТАЛКЕР')}</h3><span>{tr(preview.slot==='click'?'ЭФФЕКТ НАЖАТИЯ':preview.slot==='cursor'?'УКАЗАТЕЛЬ ДЛЯ ПК':'ПРИМЕРКА')}</span></div>{tr(preview.slot==='sound'&&<Button variant="outline" onClick={()=>previewSound(preview.id)}>{tr("ПРОСЛУШАТЬ НАБОР")}</Button>)}{tr(preview.slot==='reveal'&&<Button variant="outline" onClick={()=>setPlaying(true)}>{tr("ПОСМОТРЕТЬ АНИМАЦИЮ")}</Button>)}<strong>{tr(ownedIds.includes(preview.id)?'УЖЕ В ГАРДЕРОБЕ':preview.price+' ЖЕТОНОВ')}</strong>{tr(purchaseButton(preview))}{tr(message&&<p role="status">{tr(message)}</p>)}</>))}</DialogContent></Dialog>
 </div>;
}
