'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,Users,X,Layers,UserPlus,CalendarDays} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {useLanguage} from './language';
import {cardTitle} from '@/lib/card-language';
import {cosmetics,avatars} from '@/lib/cosmetics';

type Card={slug:string;name:string;image:string;rarity:string};
export function PublicProfiles({cards}:{cards:Card[]}){
 const {locale}=useLanguage(),en=locale==='en', [q,setQ]=useState(''),[members,setMembers]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController(),t=setTimeout(()=>fetch('/api/public-profiles?q='+encodeURIComponent(q),{signal:c.signal}).then(r=>r.json()).then(d=>setMembers(d.members||[])).catch(()=>{}),200);return()=>{clearTimeout(t);c.abort();};},[q]);
 async function open(username:string){setLoading(true);setError('');try{const r=await fetch('/api/public-profiles?username='+encodeURIComponent(username));const d=await r.json();if(!r.ok)throw Error(d.error);setSelected(d.member);}catch{setError(en?'Could not open this profile.':'Не удалось открыть профиль.');}finally{setLoading(false);}}
 const shown=useMemo(()=>selected?.cards?.map((x:any)=>({...x,card:cards.find(c=>c.slug===x.card_slug)})).filter((x:any)=>x.card),[selected,cards]);
 const equipped=selected?.equipped||{},frame=cosmetics.find(c=>c.id===equipped.frame)?.image,banner=cosmetics.find(c=>c.id===equipped.banner)?.image;
 const showcase=(selected?.showcase?.length?selected.showcase:shown?.slice(0,3).map((x:any)=>x.card_slug))||[];
 return <section className="public-profiles panel"><header><div><Users/><div><h2>{en?'PARTICIPANT PROFILES':'ПРОФИЛИ УЧАСТНИКОВ'}</h2><p>{en?'Find any registered participant by @username and view their public dossier.':'Найди любого зарегистрированного участника по @нику и открой его публичное досье.'}</p></div></div></header><label className="profile-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={en?'Search @username or name':'Поиск по @нику или имени'} aria-label={en?'Search participants':'Поиск участников'}/>{q&&<button onClick={()=>setQ('')} aria-label={en?'Clear search':'Очистить поиск'}><X/></button>}</label>{error&&<p role="alert">{error}</p>}<div className="profile-directory">{members.map(m=><button key={m.username} onClick={()=>void open(m.username)}><img src={m.avatar_url||avatars.shinigami} alt=""/><span><strong>{m.nickname||m.display_name}</strong><small>@{m.username}</small><em>{m.status}</em></span><b>{m.card_types} <Layers/></b></button>)}</div>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="public-profile-dialog"><DialogTitle>{en?'PUBLIC DOSSIER':'ПУБЛИЧНОЕ ДОСЬЕ'}</DialogTitle><DialogDescription>{en?'Only public profile information is shown.':'Показана только информация публичного профиля.'}</DialogDescription>{selected&&<article className="public-dossier"><div className="public-dossier-banner" style={banner?{backgroundImage:`linear-gradient(0deg,#070d10bb,transparent),url('${banner}')`}:undefined}/><div className="public-dossier-head"><span className="public-avatar"><img src={selected.avatar_url||avatars[selected.avatar]||avatars.shinigami} alt=""/>{frame&&<img src={frame} alt=""/>}</span><div><h2>{selected.nickname||selected.display_name}</h2><p>@{selected.username}</p><b>{selected.status}</b></div></div><p className="public-bio">{selected.bio||(en?'This stalker has not written their story yet.':'Этот сталкер ещё не написал свою историю.')}</p><div className="public-profile-stats"><span><Layers/><b>{selected.card_types}</b>{en?'different cards':'разных карт'}</span><span><Layers/><b>{selected.card_total}</b>{en?'cards total':'карт всего'}</span><span><UserPlus/><b>{selected.invites}</b>{en?'invites':'приглашений'}</span><span><CalendarDays/><b>{new Date(selected.created_at).toLocaleDateString(locale)}</b>{en?'in the Zone':'в Зоне'}</span></div><h3>{en?'COLLECTION SHOWCASE':'ВИТРИНА КОЛЛЕКЦИИ'}</h3><div className="public-showcase">{showcase.map((slug:string)=>{const entry=shown?.find((x:any)=>x.card_slug===slug);return entry&&<figure key={slug}><img src={entry.card.image} alt={cardTitle(entry.card,locale)}/><figcaption><b>{cardTitle(entry.card,locale)}</b><span>×{entry.count}</span></figcaption></figure>})}{!showcase.length&&<p>{en?'No cards on display yet.':'На витрине пока нет карт.'}</p>}</div></article>}</DialogContent></Dialog>{loading&&<p role="status">{en?'Opening dossier…':'Открываем досье…'}</p>}</section>;
}
