'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ChevronsUp,Plus,Search,ShieldCheck,X,Zap,Clock3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useLanguage} from './language';
import {cardTitle} from '@/lib/card-language';
import {pool} from '@/lib/economy';
import {upgradeChance,upgradeTarget} from '@/lib/upgrader';
import {upgradeSectorStart,upgradeNeedleAngle,upgradeDurations} from '@/lib/upgrade-presentation';
import {playCharge,playReveal,stopRevealAudio} from '@/lib/zone-soundtrack';
type Card={slug:string;name:string;rarity:string;image:string;tirazh:number|null};
export function UpgradeStation({cards,account,onAccount}:{cards:Card[];account:any;onAccount:(a:any)=>void}){
 const {locale}=useLanguage(),en=locale==='en';
 const [target,setTarget]=useState(''),[stakes,setStakes]=useState<string[]>([]),[locks,setLocks]=useState<string[]>([]),[ready,setReady]=useState(false),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[message,setMessage]=useState(''),[rotation,setRotation]=useState(0),[rankFilter,setRankFilter]=useState(1),[tab,setTab]=useState('target'),[query,setQuery]=useState(''),[inventoryQuery,setInventoryQuery]=useState('');
 const [speed,setSpeed]=useState<'fast'|'slow'>('slow'),[position,setPosition]=useState<'top'|'bottom'>('bottom'),[duration,setDuration]=useState(6000);
 const request=useRef<{id:string;target:string;stakes:string[]}|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;try{const p=JSON.parse(localStorage.getItem('s27-upgrade-presentation')||'{}');if(p.speed==='fast')setSpeed('fast');if(p.position==='top')setPosition('top');}catch{}return()=>{mounted.current=false;if(timer.current)clearTimeout(timer.current);stopRevealAudio();};},[]);
 function preferences(s:typeof speed,p:typeof position){setSpeed(s);setPosition(p);setResult(null);setRotation(0);try{localStorage.setItem('s27-upgrade-presentation',JSON.stringify({speed:s,position:p}));}catch{}}
 useEffect(()=>{setReady(false);setStakes([]);request.current=null;const controller=new AbortController();if(!account)return()=>controller.abort();fetch('/api/community',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{setLocks(d.locks);setReady(true);}).catch(()=>{if(!controller.signal.aborted)setMessage(en?'Could not check protected cards. Reopen this section.':'Не удалось проверить защиту карт. Откройте раздел заново.');});return()=>controller.abort();},[account?.discord_id]);
 const owned=Object.fromEntries((account?.cards||[]).map((c:any)=>[c.card_slug,c.count])),selection=upgradeTarget(target),blocked=busy||!!request.current;
 const chance=selection&&stakes.length?upgradeChance(selection.rank,stakes.map(s=>pool.find(c=>c[0]===s)![1]))/10000:result?.chance||0;
 const targetCard=cards.find(c=>c.slug===target),winner=cards.find(c=>c.slug===result?.slug);
 const names=en?['Uncommon','Rare','Epic','Legendary','Mythic']:['Необычная','Редкая','Эпическая','Легендарная','Мифическая'];
 function choose(value:string){setTarget(value);setStakes([]);setResult(null);setRotation(0);request.current=null;setTab('inventory');}
 function add(slug:string){setResult(null);setStakes(s=>[...s,slug]);}
 async function run(){if(busy||!stakes.length||!selection)return;setConfirm(false);setBusy(true);setResult(null);setMessage('');playCharge();const operation=request.current??{id:crypto.randomUUID(),target,stakes:[...stakes]};request.current=operation;
 try{const r=await fetch('/api/upgrader',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:operation.id,target:operation.target,stakes:operation.stakes})});const d=await r.json();if(!r.ok){request.current=null;throw Error(d.error);}const ms=window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:upgradeDurations[speed];setDuration(ms);setRotation(old=>Math.ceil(old/360)*360+(speed==='fast'?3:8)*360+upgradeNeedleAngle(d.roll,d.chance,position));timer.current=setTimeout(()=>{if(!mounted.current)return;onAccount(d.profile);setResult(d);setStakes([]);request.current=null;setBusy(false);if(d.won)playReveal(selection.rank,d.slug);else stopRevealAudio();},ms+50);
 }catch(e){setBusy(false);setMessage((e instanceof Error?e.message:String(e))+(request.current?(en?' Retry to recover this attempt.':' Повторите, чтобы восстановить эту попытку.'):''));stopRevealAudio();}}
 const available=cards.filter(c=>Number(owned[c.slug])>1&&!locks.includes(c.slug)&&pool.some(p=>p[0]===c.slug&&(!selection||p[1]<selection.rank))&&cardTitle(c,locale).toLowerCase().includes(inventoryQuery.toLowerCase()));
 const targets=cards.filter(c=>pool.some(p=>p[0]===c.slug&&p[1]===rankFilter)&&cardTitle(c,locale).toLowerCase().includes(query.toLowerCase()));
 return <section className="upgrade-v2">
 <header className="upgrade-heading"><ChevronsUp/><h1>{en?'UPGRADER':'АПГРЕЙДЕР'}</h1></header>
 <div className="upgrade-toolbar"><fieldset disabled={blocked}><legend>{en?'Spin speed':'Скорость'}</legend><button aria-pressed={speed==='slow'} onClick={()=>preferences('slow',position)}><Clock3/>{en?'Slow':'Медленно'}</button><button aria-pressed={speed==='fast'} onClick={()=>preferences('fast',position)}><Zap/>{en?'Fast':'Быстро'}</button></fieldset><fieldset disabled={blocked}><legend>{en?'Chance sector':'Сектор шанса'}</legend><button aria-pressed={position==='top'} onClick={()=>preferences(speed,'top')}>{en?'Top · 12':'Сверху · 12'}</button><button aria-pressed={position==='bottom'} onClick={()=>preferences(speed,'bottom')}>{en?'Bottom · 6':'Снизу · 6'}</button></fieldset></div>
 <div className="upgrade-stage">
 <section className="upgrade-selection input-selection"><h2>{en?'Your cards':'Ваши карты'} <small>{stakes.length}/3</small></h2><p>{en?'Duplicates used in this attempt':'Повторки для этой попытки'}</p><div className="upgrade-slot-grid">{[0,1,2].map(i=>{const c=cards.find(c=>c.slug===stakes[i]);return <button key={i} disabled={blocked} className={c?'filled':''} aria-label={c?(en?'Remove ':'Убрать ')+cardTitle(c,locale):(en?'Choose duplicate':'Выбрать повторку')} onClick={()=>{if(c){setResult(null);setStakes(s=>s.filter((_,j)=>j!==i));}else{setTab('inventory');document.getElementById('upgrade-catalog')?.scrollIntoView({behavior:'smooth',block:'start'});}}}>{c?<><img src={c.image} alt=""/><span>{cardTitle(c,locale)}</span><X className="remove-stake"/></>:<><Plus/><span>{en?'Add card':'Добавить'}</span></>}</button>;})}</div></section>
 <div className="upgrade-engine"><div className={'upgrade-wheel '+(busy?'spinning':'')} style={{'--sector-start':`${upgradeSectorStart(chance,position)}deg`,'--sector-size':`${Math.max(chance*3.6,.18)}deg`} as CSSProperties}><div className="upgrade-wheel-core"><ChevronsUp/><strong>{chance.toLocaleString(locale,{minimumFractionDigits:chance>0&&chance<.01?4:chance<1?2:0,maximumFractionDigits:4})}<small>%</small></strong><span>{en?'SUCCESS CHANCE':'ШАНС УСПЕХА'}</span></div><div className="upgrade-needle" style={{transform:`rotate(${rotation===0?(position==='bottom'?180:0):rotation}deg)`,transitionDuration:busy?`${duration}ms`:'0ms'}}/></div></div>
 <section className="upgrade-selection target-selection"><h2>{en?'Desired card':'Желаемая карта'}</h2><p>{en?'Choose a higher rarity':'Выберите редкость выше'}</p><button disabled={blocked} onClick={()=>{setTab('target');document.getElementById('upgrade-catalog')?.scrollIntoView({behavior:'smooth',block:'start'});}}>{target?<><img src={target==='mythic'?'/classified.svg':targetCard?.image} alt=""/><strong>{target==='mythic'?(en?'Random mythic':'Случайный мифик'):targetCard?cardTitle(targetCard,locale):''}</strong></>:<><ChevronsUp/><span>{en?'Choose a target':'Выбрать цель'}</span></>}</button></section>
 <Button className="upgrade-action" disabled={!account||!ready||busy||!stakes.length||!target} onClick={()=>request.current?void run():setConfirm(true)}><ChevronsUp/>{busy?(en?'UPGRADING…':'АПГРЕЙД…'):request.current?(en?'RECOVER RESULT':'ВОССТАНОВИТЬ РЕЗУЛЬТАТ'):(en?'UPGRADE':'УЛУЧШИТЬ')}</Button>
 </div><p className="upgrade-safety"><ShieldCheck/>{en?'Last copies and starred cards are protected. Staked duplicates are spent on either outcome.':'Последние копии и избранные защищены. Поставленные повторки списываются при любом результате.'}</p>
 {message&&<p role="alert" className="upgrade-message">{message}</p>}{result&&<div role="status" className={'upgrade-outcome '+(result.won?'success':'failure')}><h2>{result.won?(en?'UPGRADE SUCCESSFUL':'АПГРЕЙД УСПЕШЕН'):(en?'UPGRADE FAILED':'АПГРЕЙД НЕ УДАЛСЯ')}</h2><p>{result.won?(target==='mythic'?(en?'A classified mythic is now in your collection.':'Засекреченный мифик уже в вашей коллекции.'):winner?cardTitle(winner,locale):''):(en?'Staked duplicates were consumed. Your last copies are safe.':'Повторки списаны. Последние экземпляры сохранены.')}</p></div>}
 <div id="upgrade-catalog" className="upgrade-catalog" data-tab={tab}><div className="upgrade-mobile-tabs" role="tablist" aria-label={en?'Cards':'Карты'}>{['inventory','target'].map(id=><button key={id} role="tab" aria-selected={tab===id} aria-controls={'upgrade-'+id} onClick={()=>setTab(id)}>{id==='inventory'?(en?'My cards':'Мои карты'):(en?'Desired cards':'Желаемые карты')}</button>)}</div>
 <section id="upgrade-inventory" className="upgrade-inventory"><header><h2>{en?'My duplicates':'Мои повторки'}</h2><span>{available.length}</span></header><label className="upgrade-search"><Search/><input value={inventoryQuery} onChange={e=>setInventoryQuery(e.target.value)} placeholder={en?'Find a card':'Найти карту'} aria-label={en?'Search inventory':'Поиск в инвентаре'}/></label>{!account?<div className="upgrade-empty"><ShieldCheck/><h3>{en?'Sign in to use your cards':'Войдите, чтобы использовать карты'}</h3><p>{en?'Open your profile and connect Discord.':'Откройте досье и подключите Discord.'}</p></div>:!available.length?<div className="upgrade-empty"><p>{en?'No eligible duplicates. First copies and favourites cannot be staked.':'Нет подходящих повторок. Первые экземпляры и избранные нельзя поставить.'}</p></div>:<><p className="upgrade-catalog-hint">{selection?(en?'Select up to three cards':'Выберите до трёх карт'):(en?'Choose a desired card first':'Сначала выберите желаемую карту')}</p><div className="upgrade-card-grid">{available.map(c=>{const remaining=Number(owned[c.slug])-1-stakes.filter(s=>s===c.slug).length;return <button key={c.slug} disabled={!selection||!ready||blocked||remaining<1||stakes.length===3} onClick={()=>add(c.slug)} aria-label={`${cardTitle(c,locale)} ×${remaining}`}><span className="upgrade-quantity">×{remaining}</span><img src={c.image} alt="" loading="lazy"/><strong>{cardTitle(c,locale)}</strong></button>;})}</div></>}</section>
 <section id="upgrade-target" className="upgrade-target-catalog"><header><h2>{en?'Desired cards':'Желаемые карты'}</h2></header><label className="upgrade-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={en?'Find a card':'Найти карту'} aria-label={en?'Search targets':'Поиск цели'}/></label><div className="upgrade-rarity-tabs">{[1,2,3,4].map(r=><button key={r} disabled={blocked} aria-pressed={rankFilter===r} onClick={()=>setRankFilter(r)}>{names[r]}</button>)}</div><div className="upgrade-card-grid">{rankFilter===4?<button disabled={blocked} aria-pressed={target==='mythic'} onClick={()=>choose('mythic')}><img src="/classified.svg" alt=""/><strong>{en?'Random mythic':'Случайный мифик'}</strong></button>:targets.map(c=><button key={c.slug} disabled={blocked} aria-pressed={target===c.slug} onClick={()=>choose(c.slug)}><img src={c.image} alt="" loading="lazy"/><strong>{cardTitle(c,locale)}</strong></button>)}</div>{rankFilter!==4&&!targets.length&&<p className="upgrade-empty">{en?'No cards found':'Карты не найдены'}</p>}</section></div>
 <details className="upgrade-help"><summary>{en?'How the chance is calculated':'Как рассчитывается шанс'}</summary><p>{en?'The upgrader is a risky side activity; caches remain the main way to obtain valuable cards. Each staked duplicate is an independent attempt. Direct upgrades begin at 6% for Rare, 1.2% for Epic, 0.25% for Legendary and only 0.01% for Mythic. Larger rarity jumps are much harder. Two cards receive a 3% combination bonus and three receive 8%; the final chance never exceeds 25%. Speed and sector position are visual only.':'Апгрейдер — рискованная дополнительная механика; главным способом получения ценных карт остаются тайники. Каждая повторка считается отдельной попыткой. Прямой переход начинается с 6% для редкой, 1,2% для эпической, 0,25% для легендарной и всего 0,01% для мифической. Прыжки через несколько редкостей намного сложнее. Две карты получают бонус комплекта 3%, три — 8%; итоговый шанс никогда не превышает 25%. Скорость и положение сектора влияют только на анимацию.'}</p><code>P = min(25%; (1 − ∏(1 − pᵢ)) × bonus)</code></details>
 <Dialog open={confirm} onOpenChange={setConfirm}><DialogContent className="system-dialog"><DialogTitle>{en?'CONFIRM STAKE':'ПОДТВЕРДИТЬ СТАВКУ'}</DialogTitle><DialogDescription>{en?`You will spend ${stakes.length} duplicate(s). Success chance: ${chance}%. Failure does not return the stake.`:`Вы потратите ${stakes.length} повторки. Шанс успеха: ${chance}%. При неудаче ставка не возвращается.`}</DialogDescription><Button onClick={run}>{en?'CONFIRM UPGRADE':'ПОДТВЕРДИТЬ АПГРЕЙД'}</Button><Button variant="outline" onClick={()=>setConfirm(false)}>{en?'CANCEL':'ОТМЕНА'}</Button></DialogContent></Dialog>
 </section>;
}
