// Public descriptions never disclose an unopened classified dossier.
const english:Record<string,[string,string]>={
 silverhand:['SILVERHAND','A mechanical arm and a stubborn will keep the squad moving when the Zone closes every ordinary route.'],
 vlad:['VLAD','The Inquisitor holds the line while the squad searches for a path through the ruins.'],
 shinigami:['SHINIGAMI','Shiga advances through the anomalies, reading the silence before the first shot.'],
 zuban:['ZUBAN','Fang brings a familiar voice to the campfire. Beyond the shelter, even a quiet evening can become a raid.'],
 oleg:['OLEG','Powerlifter carries the weight of the expedition, guarding the others when the route turns dangerous.'],
 qwtep:['QWTEP','Magarych keeps the engine alive. Broken roads are another reason to find a different route.'],
 myatus:['MYATUS','Menthol watches the approaches from cover. The squad moves because someone is watching the horizon.'],
 lexa:['LEXA','Jackson stays beside the squad through the entire raid: not every act of courage needs a separate command.'],
 'burnt-map':['BURNT MAP','Fire erased the easy landmarks, but a surviving fragment still points beyond the perimeter.'],
 silence:['PERIOD OF SILENCE','The channels fall quiet, yet the archive remains. A pause is part of the story, not its end.'],
 signal27:['SIGNAL 27','A recurring signal connects isolated records. Someone on the other side is still listening.'],
 everfrost:['EVERFROST','Cold changed more than the scenery: it reshaped the entire server. This dossier preserves that chapter.'],
 'vent-shaft':['VENTILATION SHAFT','The squad gathers at the shaft before entering the underground complex. The narrow passage offers no easy retreat.'],
 'stalker-tokens':['STALKER TOKENS','Nine tokens remain as signs of the squad: names carried beyond the perimeter, not forgotten in it.'],
 'new-coordinates':['NEW COORDINATES','After evacuation, the terminal lights up with an unfamiliar destination. Survival closes one mission and opens another.'],
 'silverhand-door':['SILVERHAND: HERMETIC DOOR','Silverhand stops the mechanical gates before overload, buying the squad the seconds needed to pass.'],
 'qwtep-route':['QWTEP: UNDERGROUND ROUTE','Energy modules must cross the ruined tunnels. Qwtep finds the route that the surface maps cannot show.'],
 'myatus-control':['MYATUS: ROUTE CONTROL','From the broken structures above, Myatus covers the squad’s movement through the complex.'],
 'lexa-shoulder':['LEXA: SHOULDER TO SHOULDER','Lexa remains with the squad until evacuation. The route is survived together, not alone.'],
 'manager-protocol':['MANAGER: SECRET PROTOCOL','The decoded emergency protocol gives nine separate paths a common objective.'],
 'first-sirens':['FIRST SIRENS','Sirens announce the beginning of Shadow of Chernobyl. The expedition crosses from preparation into action.'],
 'noosphere-crack':['NOOSPHERE CRACK','A laboratory experiment fractures the balance above the Zone. The disturbance reaches far beyond its source.'],
 'super-emission':['SUPER EMISSION','An accelerated emission threatens to cross the perimeter. The squad must act before the warning becomes reality.'],
 'nine-bunker':['NINE IN THE BUNKER','Nine different routes converge in one underground node. Here the expedition becomes a single squad.'],
 evacuation:['EVACUATION','All nine leave the complex moments before the explosion. The archive records an escape, not an ending.'],
 'crown-emission':['CROWN OF EMISSION','The crown preserves the trace of the Zone’s violent energy as an event trophy.'],
 revival:['REVIVAL','The project returns after a pause. Familiar signals come back online, opening another chapter of NE S27.'],
 wastelands:['WASTELANDS','The post-apocalyptic chapter becomes a bridge to the new Zone. Its dossier preserves the season’s identity.'],
 'hall-of-fame':['HALL OF FAME','The hall remembers people and events that left a lasting mark on the community.'],
 'zuban-return':['RETURN OF ZUBAN','A familiar name returns to the community’s story. This card marks Zuban’s return and his personal secret prize.'],
 'world-cup':['WORLD CUP','Competition brings the community together. The trophy preserves the memory of its World Cup chapter.'],
 solstice:['SOLSTICE','A transition between chapters: time to pause, gather the community and prepare for what follows.'],
 'fallen-angel':['FALLEN ANGEL','A themed chapter of NE S27, preserved as a separate record in the seasonal collection.'],
 'dark-side':['DARK SIDE','The dark side of a server chapter: its atmosphere and identity remain in the seasonal archive.'],
 'light-side':['LIGHT SIDE','The light side of a server chapter: another perspective within the shared history of NE S27.'],
};
export function cardTitle(card:{slug:string;name:string;image:string;nameEn?:string},locale:string){return card.image==='/classified.svg'?(locale==='en'?'CLASSIFIED':'ЗАСЕКРЕЧЕНО'):locale==='en'?(card.nameEn??english[card.slug]?.[0]??card.name):card.name;}
export function cardLore(card:{slug:string;quote?:string;image:string;quoteEn?:string},locale:string){if(card.image==='/classified.svg')return locale==='en'?'The dossier unlocks after obtaining this card.':'Досье откроется после получения этой карты.';return locale==='en'?(card.quoteEn??english[card.slug]?.[1]??'A record from the NE S27 collection.'):(card.quote&&card.quote!=='███'&& !card.quote.includes('будет добавлен')?card.quote:'Закрытое досье архива NE S27. Полученная карта сохраняет запись в личной коллекции.');}
