'use client';
export type AudioPrefs={volume:number;clicks:number;effects:number;background:number;muted:boolean;pack:string;useEquipped:boolean};
export const defaultAudio:AudioPrefs={volume:55,clicks:42,effects:65,background:55,muted:false,pack:'soft',useEquipped:true};
let prefs={...defaultAudio},ctx:AudioContext|null=null,master:GainNode|null=null,clickBus:GainNode|null=null,effectBus:GainNode|null=null;
const buffers=new Map<string,Promise<AudioBuffer>>(),activeEffects=new Set<AudioBufferSourceNode>();let effectEpoch=0,lastClick=0;
let arrivalPlayed=false;
let ambient:AudioBufferSourceNode|null=null,ambientBus:GainNode|null=null,ambientLoading=false;
function syncAmbient(){if(!ctx||ctx.state!=='running')return;if(!ambientBus){ambientBus=ctx.createGain();ambientBus.connect(master!);}ambientBus.gain.setTargetAtTime(document.hidden?0:(prefs.background??55)/100*.65,ctx.currentTime,.7);if(ambient||ambientLoading||prefs.muted||!prefs.background)return;ambientLoading=true;void buffer('zone-ambient').then(b=>{if(!ctx)return;ambient=ctx.createBufferSource();ambient.buffer=b;ambient.loop=true;ambient.connect(ambientBus!);ambient.start();}).catch(()=>{}).finally(()=>{ambientLoading=false;});}
export const freeSounds=[{id:'soft',name:'ПУПЫРЧАТАЯ ПЛЁНКА',description:'Мягкий короткий хлопок без звона.'},{id:'glass',name:'ТИХИЙ ЗАТВОР',description:'Лёгкий щелчок камеры без резкого хвоста.'},{id:'relay',name:'ПОЛЕВОЕ РЕЛЕ',description:'Приглушённое реле полевого прибора.'}];
export function configureAudio(value:AudioPrefs){prefs={...defaultAudio,...value};if(ctx){master?.gain.setTargetAtTime(value.muted?0:value.volume/100,ctx.currentTime,.03);clickBus?.gain.setTargetAtTime(value.clicks/100,ctx.currentTime,.03);effectBus?.gain.setTargetAtTime(value.effects/100,ctx.currentTime,.03);syncAmbient();}}
function startCampfire(){syncAmbient();if(!ctx||ctx.state!=='running'||arrivalPlayed||prefs.muted)return;arrivalPlayed=true;void play('arrival-fire','effects');}
export function initializeArrivalAudio(){unlockAudio();const begin=()=>{unlockAudio();};document.addEventListener('pointerdown',begin,{passive:true});document.addEventListener('keydown',begin);document.addEventListener('visibilitychange',syncAmbient);return()=>{document.removeEventListener('pointerdown',begin);document.removeEventListener('keydown',begin);document.removeEventListener('visibilitychange',syncAmbient);};}
function buffer(name:string){if(!buffers.has(name))buffers.set(name,fetch('/audio/'+name+((name.startsWith('card-')||name==='zone-ambient'||name==='vault-reveal-5')?'.mp3':'.wav')+'?v=zone23').then(r=>{if(!r.ok)throw Error('Audio unavailable');return r.arrayBuffer();}).then(b=>ctx!.decodeAudioData(b)).catch(e=>{buffers.delete(name);throw e;}));return buffers.get(name)!;}
export function unlockAudio(){try{if(!ctx){ctx=new AudioContext();master=ctx.createGain();clickBus=ctx.createGain();effectBus=ctx.createGain();clickBus.connect(master);effectBus.connect(master);master.connect(ctx.destination);configureAudio(prefs);for(const n of ['click-soft','click-glass','click-relay','click-paper','click-switch','click-rain','vault-charge','case-charge','case-result',...Array.from({length:4},(_,i)=>'vault-stage-'+i),...Array.from({length:5},(_,i)=>'vault-reveal-'+i)])void buffer(n).catch(()=>{});}if(ctx.state==='suspended')void ctx.resume().then(startCampfire).catch(()=>{});startCampfire();}catch{}}
async function play(name:string,channel:'clicks'|'effects',rate=1){unlockAudio();if(!ctx||prefs.muted)return;const epoch=effectEpoch;try{const b=await buffer(name);if(prefs.muted||channel==='effects'&&epoch!==effectEpoch)return;if(ctx.state==='suspended')await ctx.resume();const s=ctx.createBufferSource();s.buffer=b;s.playbackRate.value=rate;s.connect(channel==='clicks'?clickBus!:effectBus!);if(channel==='effects')activeEffects.add(s);s.onended=()=>{activeEffects.delete(s);s.disconnect();};s.start();}catch{}}
export function stopRevealAudio(){effectEpoch++;for(const s of activeEffects){try{s.stop();}catch{}}activeEffects.clear();}
function clickName(pack:string){return pack==='sound-paper'?'click-paper':pack==='sound-switch'?'click-switch':pack==='sound-rain'?'click-rain':pack==='glass'||pack==='sound-crystal'?'click-glass':pack==='relay'||pack==='sound-vault'?'click-relay':'click-soft';}
export function playClick(){if(Date.now()-lastClick<45)return;lastClick=Date.now();void play(clickName(prefs.pack),'clicks',prefs.pack==='sound-orbit'?.8:prefs.pack==='sound-crystal'?1.2:1);}
export function previewSound(pack:string){void play(clickName(pack),'clicks');}
export function playCharge(){void play('case-charge','effects');}
export function playPhase(phase:number){void play('vault-stage-'+Math.max(0,Math.min(3,phase)),'effects');}
export function playReveal(rank:number,slug?:string){void play(slug&&/^[a-z0-9-]+$/.test(slug)?'card-'+slug:'vault-reveal-'+Math.max(0,Math.min(5,rank)),'effects');}
export function playWalkout(stage:number,rank=0,slug?:string){if(stage===5){playReveal(rank,slug);return;}void play(stage===0?'vault-charge':'vault-stage-'+(stage-1),'effects');}
