import {getD1,getSessionUser,hasAdminAccess,profilePayload} from '@/lib/s27-server';
import {pool} from '@/lib/economy';
export async function GET(r:Request){try{const u=await getSessionUser(r);if(!u||!(await hasAdminAccess(u.discord_id)))return Response.json({error:'Нет доступа'},{status:403});const db=getD1();const q=(new URL(r.url).searchParams.get('q')||'').replace(/^@/,'').slice(0,100);const members=await db.prepare("SELECT u.discord_id,u.username,u.display_name,u.tokens,u.fragments,u.created_at,r.created_at AS registered_at FROM users u LEFT JOIN site_registrations r ON r.user_id=u.discord_id WHERE (?='' OR instr(lower(u.username),lower(?))>0 OR instr(lower(u.display_name),lower(?))>0 OR u.discord_id=?) ORDER BY r.created_at DESC,u.created_at DESC LIMIT 100").bind(q,q,q,q).all();const audit=await db.prepare("SELECT actor_id,action,target_id,payload,created_at FROM audit_log"+' ORDER BY id DESC LIMIT 50').all();return Response.json({members:members.results,audit:audit.results},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Не удалось загрузить участников'},{status:503});}}
export async function POST(r:Request){try{const u=await getSessionUser(r);if(!u||!(await hasAdminAccess(u.discord_id)))return Response.json({error:'Нет доступа'},{status:403});const b=await r.json();if(typeof b.target!=='string')return Response.json({error:'Тестовый администратор управляет только тестовыми аккаунтами'},{status:403});
 if(!['coupons','tokens','card'].includes(b.kind)||!Number.isInteger(b.amount)||b.amount<1||b.amount>(b.kind==='card'?100:100000)||typeof b.reason!=='string'||!b.reason.trim()||typeof b.requestId!=='string'||! /^[a-f0-9-]{36}$/.test(b.requestId))return Response.json({error:'Укажите тип, количество и причину выдачи'},{status:400});
 if(b.kind==='card'&&!pool.some(c=>c[0]===b.cardSlug))return Response.json({error:'Карта исключена из коллекции'},{status:400});
 const db=getD1(),now=Date.now(),id=u.discord_id+':grant:'+b.requestId;const target=await db.prepare('SELECT discord_id FROM users WHERE discord_id=?').bind(b.target).first();if(!target)return Response.json({error:'Участник не найден'},{status:404});const prev=await db.prepare('SELECT id FROM operations WHERE id=?').bind(id).first();if(prev)return Response.json({ok:true});
 const statements=[db.prepare("INSERT INTO operations(id,user_id,action,result,valid,created_at) VALUES (?,?,'admin.grant','{}',1,?)").bind(id,u.discord_id,now)];
 if(b.kind==='card')statements.push(db.prepare('INSERT INTO user_cards(user_id,card_slug,count,updated_at) VALUES (?,?,?,?) ON CONFLICT(user_id,card_slug) DO UPDATE SET count=count+excluded.count,updated_at=excluded.updated_at').bind(b.target,b.cardSlug,b.amount,now));
 else statements.push(db.prepare(b.kind==='coupons'?'UPDATE users SET tokens=tokens+?,updated_at=? WHERE discord_id=?':'UPDATE users SET fragments=fragments+?,updated_at=? WHERE discord_id=?').bind(b.amount,now,b.target));
 statements.push(db.prepare("INSERT INTO audit_log(actor_id,action,target_id,payload,created_at) VALUES (?,'admin.grant',?,?,?)").bind(u.discord_id,b.target,JSON.stringify({kind:b.kind,card:b.cardSlug,amount:b.amount,reason:b.reason.slice(0,300)}),now));await db.batch(statements);return Response.json({ok:true,profile:await profilePayload(u.discord_id)});
 }catch{return Response.json({error:'Выдача не выполнена или запрос уже обработан'},{status:409});}}
