import {getD1,getSessionUser,isAdmin,adminIds,getRuntimeValue} from '@/lib/s27-server';
const metrics={tokens:'tokens',packs:'packs',invites:'invites',cards:'cards'} as const;
async function staffIds(){const row=await getD1().prepare("SELECT value FROM site_settings WHERE key='bridge:managers'").first<{value:string}>();return [...new Set([...adminIds(),...(getRuntimeValue('MANAGER_DISCORD_IDS')||'').split(',').map((s:string)=>s.trim()).filter(Boolean),...(row?JSON.parse(row.value):[])])];}
export async function GET(r:Request){try{
 const url=new URL(r.url),admin=url.searchParams.get('admin')==='1';if(admin){const user=await getSessionUser(r);if(!user||!isAdmin(user.discord_id))return Response.json({error:'No access'},{status:403});}
 const metric=metrics[url.searchParams.get('metric') as keyof typeof metrics]||'tokens',q=(url.searchParams.get('q')||'').replace(/^@/,'').slice(0,100),staff=await staffIds(),db=getD1();
 const fields="u.discord_id,u.username,u.display_name,u.fragments AS tokens,u.pack_count AS packs,COALESCE(c.cards,0) AS cards,COALESCE(r.invites,0) AS invites,CASE WHEN h.value='true' THEN 1 ELSE 0 END AS hidden";
 const rows=await db.prepare(`SELECT ${fields} FROM users u JOIN site_registrations s ON s.user_id=u.discord_id LEFT JOIN (SELECT user_id,COUNT(*) AS cards FROM user_cards WHERE count>0 GROUP BY user_id) c ON c.user_id=u.discord_id LEFT JOIN (SELECT referrer_user_id,COUNT(*) AS invites FROM referrals WHERE status='verified' GROUP BY referrer_user_id) r ON r.referrer_user_id=u.discord_id LEFT JOIN site_settings h ON h.key='leaderboard:hidden:'||u.discord_id WHERE u.discord_id NOT LIKE 'lab:%' AND (?=1 OR (u.discord_id NOT IN (SELECT value FROM json_each(?)) AND COALESCE(h.value,'false')!='true')) AND (?='' OR instr(lower(u.username),lower(?))>0 OR instr(lower(u.display_name),lower(?))>0 OR u.discord_id=?) ORDER BY ${metric} DESC,u.username COLLATE NOCASE,u.discord_id LIMIT 50`).bind(admin?1:0,JSON.stringify(staff),q,q,q,q).all<any>();
 return Response.json({members:rows.results.map((row:any)=>admin?{...row,staff:staff.includes(row.discord_id)}:{username:row.username,displayName:row.display_name,score:row[metric]}),metric,updatedAt:Date.now()},{headers:{'Cache-Control':'no-store'}});
 }catch(e){console.error('leaderboard unavailable',e);return Response.json({error:'Leaderboard unavailable'},{status:503});}}
export async function POST(r:Request){try{const u=await getSessionUser(r);if(!u||!isAdmin(u.discord_id))return Response.json({error:'No access'},{status:403});const b=await r.json();if(typeof b.hidden!=='boolean'||typeof b.userId!=='string'||!/^\d{16,22}$/.test(b.userId))return Response.json({error:'Invalid member'},{status:400});const db=getD1();if(!await db.prepare('SELECT user_id FROM site_registrations WHERE user_id=?').bind(b.userId).first())return Response.json({error:'Member not found'},{status:404});const now=Date.now();await db.batch([db.prepare('INSERT INTO site_settings(key,value,updated_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind('leaderboard:hidden:'+b.userId,JSON.stringify(b.hidden),now),db.prepare('INSERT INTO audit_log(actor_id,action,target_id,payload,created_at) VALUES (?,?,?,?,?)').bind(u.discord_id,'leaderboard.visibility',b.userId,JSON.stringify({hidden:b.hidden}),now)]);return Response.json({ok:true});}catch{return Response.json({error:'Could not save visibility'},{status:503});}}
